### ISSUE TITLE
Fix path to make

### ISSUE THREAD

**Issue by worksofliam** [IBM/ibmi-bob#104]
Much like we do for `bash` in `Makefile`, should we also set the path to the version of GNU Make available through yum?

Example for `bash`:

https://github.com/IBM/ibmi-bob/blob/e9124605e79d2019f11f9f706f80d2c838ebbcba/mk/Makefile#L1

Add specific path here?

https://github.com/IBM/ibmi-bob/blob/44a83fa6b225112f3c9bd916523b053894dfc44f/makei/build.py#L69

Change:

`make` to `/QOpenSys/pkgs/bin/make`

**Comment by edmundreinhardt** [comment]
Tongkun, please make this a priority, it should be pretty simple.

**Comment by edmundreinhardt** [comment]
Just run into this making the Merlin Ci/CD fail
