### ISSUE TITLE
Developer setup instructions

### ISSUE THREAD

**Issue by worksofliam** [IBM/ibmi-bob#112]
I think CONTRIBUTING needs some developer setup instructions

* software requirements
* hardware requirements
   * do we need an IBM i to develop ibmi-bob? can we develop it and run `--just-print`

**Comment by edmundreinhardt** [comment]
@worksofliam 
In order gmake to work, doesn't it have to have access to the target object to check its timestamp, or is there a way of mocking it to say that the target always does not exist

**Comment by edmundreinhardt** [comment]
this has been addressed by Tongkun
`nox -s dev` sets you up as documented here https://ibm.github.io/ibmi-bob/#/contributing/getting-started
