### ISSUE TITLE
Trouble Installing Bob on IBM i

### ISSUE THREAD

**Issue by beckhamrryyaann** [IBM/ibmi-bob#124]
I thought I would leave a comment here just incase anyone else runs across this issue.   I was trying to install Bob and it told me it was not an available package.  "No package Bob available"  Error: Nothing to do
After researching I had to install an update to the yum package itself and also install the package "ca-certificates-mozilla".

After updating yum and install the ca certificate mozilla i was able to install Bob.

**Comment by edmundreinhardt** [comment]
Or our prerequisites page we have a section and link showing how to install open source technologies using ACS
https://ibm.github.io/ibmi-bob/#/getting-started/prerequisites?id=install-ibm-i-open-source-technologies
