### ISSUE TITLE
CRTSQLRPGI precompile is limited to 132 characters per record

### ISSUE THREAD

**Issue by beckhamrryyaann** [IBM/ibmi-bob#128]
I am using crtsqlrpgi to create a program.  The program is stored in IFS and I am not worried about record lengths.  This is the benefit of using IFS to store source.  I have several lines that go past 132 characters.
I got a compile error RNF0733.  Can Bob create the temporary source file that holds the sql pre compile to be way larger than 132?  Please see this link for IBM's recommendations.

[IBM Doc on RNF0733](https://www.ibm.com/docs/en/rdfi/9.6.0?topic=SSAE4W_9.6.0/com.ibm.etools.iseries.ilerpg.doc/RNF0733.htm)

**Comment by edmundreinhardt** [comment]
Please upgrade to 2.4.0 of bob
As you can see in the release notes https://github.com/IBM/ibmi-bob/releases
we have included the pull https://github.com/IBM/ibmi-bob/pull/116
which updates the RUNSQLSTM margin to 1024.
Hopefully that is sufficient.

**Comment by edmundreinhardt** [comment]
Hmm but you say you are seeing this on CRTSQLRPGI.  This is a separate issue.  Let me investigate.

**Comment by edmundreinhardt** [comment]
Sadly this is a limitation of the CRTSQLRPGI command as documented in the manual 
https://www.ibm.com/docs/en/i/7.5?topic=ssw_ibm_i_75/cl/crtsqlrpgi.htm#CRTSQLRPGI.SRCSTMF


```Source stream file (SRCSTMF)
Specifies the path name to the file that contains the RPG source statements and SQL statements. The path name can be either absolute or relative.
````
Source text must be in positions 1 to 100. Characters after position 100 will be ignored.
```

I will apply pressure on the maintainers of that command to loosen that restriction.

**Comment by edmundreinhardt** [comment]
I recommend submitting and Idea at https://ibm-power-systems.ideas.ibm.com/?category=7078723489984938735
with real customers voting on this idea, it will demonstrate customer demand.

**Comment by edmundreinhardt** [comment]
Before I close this issue, please open the idea and post back the link so others will discover this and vote it up

**Comment by beckhamrryyaann** [comment]
That is unfortunate.  Hopefully they will loosen that restriction.   That seems silly for developers using the ifs to compile source.  Thank you for the update.

**Comment by beckhamrryyaann** [comment]
Will do.  Thank you.

**Comment by beckhamrryyaann** [comment]
The idea has been submitted to IBM for review at [Increase line size of SRCSTMF on the CRTSQLRPGI command.](https://ibm-power-systems.ideas.ibm.com/ideas/IBMI-I-3389)
Anyone coming across this issue please visit this page and vote for this idea. Thank you!

**Comment by edmundreinhardt** [comment]
I am talking to the compiler developers and they are somewhat skeptical.  Could you give me the example code so that we can verify what caused the compiler error?

**Comment by edmundreinhardt** [comment]
From the compiler developers:
```
If the source has **FREE on the first line, the SQL precompiler supports lines of any length, the same as the RPG compiler. The SQL precompiler was updated to support long lines with **FREE at the same time, for the same releases, as the ILE RPG compiler.

I think it's just the documentation that's wrong.
```
Now investigating if it is the RPGPPOTP of *LVL2 that is causign this

**Comment by edmundreinhardt** [comment]
it failed with *LVL2 when I didn't create QTEMP/QSQLPRE in a advance. If the precompiler creates that file for *LVL1 or *LVL2, it creates it with record length 112.

The precompiler can't scan the source in advance before doing the preprocess for *LVL1 or *LVL2 because it doesn't know what copy files will be placed in the output. So it always creates it with record length 112.
The help for the RPG preprocessor message RNF0733 says
Recovery . . . : If the CRTSQLRPGI command is used with a value of *LVL1 or *LVL2 for the RPGPPOPT parameter, create file QTEMP/QSQLPRE with a sufficiently long record length prior to using the CRTSQLRPGI command again.

So BOB could create QTEMP/QSQLPRE with whatever is the maximum record length prior to doing a compile with RPGPPOPT(*LVL1) or *LVL2.

Maximum is RCDLEN(32766)

In the meantime you can work around this by not using *LVL1 or *LVL2

**Comment by edmundreinhardt** [comment]
The RPG compiler has created a new parameter PPMINOUTLN to address this.
The compiler will find the longest line length in the main source.  However the compiler will not scan include files if their lines are longer. By default the value of 100 will be used unless this parameter is used.  Not that you can CHGCMDDFT to make this parameter always specify a longer value.

BOB itself will support this parameter through addressing the issue https://github.com/IBM/ibmi-bob/issues/181

**Comment by beckhamrryyaann** [comment]
Great news!  Thanks for the update.Sent from my iPhoneOn Dec 8, 2022, at 5:54 PM, Edmund Reinhardt ***@***.***> wrote:﻿
The RPG compiler has created a new parameter PPMINOUTLN to address this.
The compiler will find the longest line length in the main source.  However the compiler will not scan include files if their lines are longer. By default the value of 100 will be used unless this parameter is used.  Not that you can CHGCMDDFT to make this parameter always specify a longer value.
BOB itself will support this parameter through addressing the issue #181
