### ISSUE TITLE
Use of variable in preUsrLibl causing problems - only first char is used.

### ISSUE THREAD

**Issue by zkarj735** [IBM/ibmi-bob#129]
I'm trying to get my first ibmi-bob project to build and have got this error. I'll be the first to admit I'm making lots of mistakes but this reads like an issue with the ibmi-bob file, not mine.

```
Current library: QGPL
Library list: QTEMP DAGSW DAGDTA QGPL TAATOOL IOMSDTA
Commands:
		OPT=*EVENTF BUILDLIB=DEMOTEST /QOpenSys/pkgs/bin/makei build

> make -k BUILDVARSMKPATH="/tmp/tmpd74k1ph3" -k BOB="/QOpenSys/pkgs/lib/bob" -f "/QOpenSys/pkgs/lib/bob/mk/Makefile" all
"/QOpenSys/pkgs/lib/bob/mk/Makefile", line 10: make: Dependency line needs colon or double colon operator.
make: Equal sign not found in macro substitution.

Objects:             0 failed 0 succeed 0 total
Build Completed!

Fetching errors from QGPL/iproj.
```

**Comment by beckhamrryyaann** [comment]
I am also getting the same error.  See issue #126 .

**Comment by zkarj735** [comment]
My issue is also when running from VSCode with similar configurations.

**Comment by edmundreinhardt** [comment]
I don't recommend using QGPL as your current library you are compiling into.  Wouldn't you prefer compiling into DAGSW

**Comment by TongkunZhang** [comment]
Which version of Bob are you running on?

I assume this is because the gnu make is not picked up correctly when running from Code for i. 
Bob (>=2.3.10) now fully qualifies the path to the GNU make (see #108) and let me know if that still does not work in the latest version.

<img width="1234" alt="Using the default make to reproduce the error" src="https://user-images.githubusercontent.com/17009902/188978935-2d754715-2d09-4c78-9e2d-eca0d5cc47e4.png">

**Comment by zkarj735** [comment]
> I don't recommend using QGPL as your current library you are compiling into. Wouldn't you prefer compiling into DAGSW

The QGPL current library was also a puzzlement. Here's my `iproj.json`
```
{
    "version": "0.0.1",
    "description": "Alerting framework",
    "objlib": "&BUILDLIB",
    "curlib": "&BUILDLIB"
}
```
And my build command
```
OPT=*EVENTF BUILDLIB=DEMOTEST /QOpenSys/pkgs/bin/makei build
```

**Comment by zkarj735** [comment]
> Which version of Bob are you running on?

` 2.3.9-1`

I will update to `2.3.10` and retest.

**Comment by zkarj735** [comment]
The repo does not see later than 2.3.9.
```
bob.ppc64                       2.3.9-1                   @ibmi-release
```

**Comment by edmundreinhardt** [comment]
> > I don't recommend using QGPL as your current library you are compiling into. Wouldn't you prefer compiling into DAGSW
> 
> The QGPL current library was also a puzzlement. Here's my `iproj.json`
> 
> ```
> {
>     "version": "0.0.1",
>     "description": "Alerting framework",
>     "objlib": "&BUILDLIB",
>     "curlib": "&BUILDLIB"
> }
> ```
> 
> And my build command
> 
> ```
> OPT=*EVENTF BUILDLIB=DEMOTEST /QOpenSys/pkgs/bin/makei build
> ```

@worksofliam Liam, can you refresh my memory here.  I seem to remember that Code for i is NOT respecting objlib and curlib in iproj.json.  Can you chime in with the right way to do things in Code for i?

**Comment by zkarj735** [comment]
I should also have included my action per `actions.json`.
```
    {
        "name": "TEST Bob",
        "command": "OPT=*EVENTF BUILDLIB=DEMOTEST /QOpenSys/pkgs/bin/makei build",
        "extensions": [
          "GLOBAL"
        ],
        "environment": "pase",
        "deployFirst": true
      }
```

**Comment by zkarj735** [comment]
I updated to 2.4.0.1 (thanks to advice on #130) and note the current library is still not honoured.

**Comment by worksofliam** [comment]
The correct way for this to work is to set the Current Library in Code for IBM i as that reflects on CURLIB and BUILDLIB

**Comment by edmundreinhardt** [comment]
FYI my actions.js looks like
```
[
    {
        "command": "err=*EVENTF lib1=&CURLIB makei build",
        "deployFirst": true,
        "environment": "pase",
        "extensions": [
            "GLOBAL"
        ],
        "name": "bob build"
    },
    {
        "command": "err=*EVENTF makei compile -f &BASENAME -e lib1=&CURLIB",
        "deployFirst": true,
        "environment": "pase",
        "extensions": [
            "GLOBAL"
        ],
        "name": "bob compile"
    }
]
```

**Comment by edmundreinhardt** [comment]
Note how I am setting my build lib to &CURLIB so it is set by Code for IBM i

**Comment by zkarj735** [comment]
This gets around the errors, but the examples/documentation need improving to state this.

It means switching between test and production builds/compiles is more fiddly than I was hoping. I had a choice of actions for this when using raw makefiles, as the variable was simply set per action.

Also, your use of `-f &BASENAME` fails with lower case source file names. I like the idea of keeping file names lower case as it makes it much easier to distinguish them from object names in the Rules file.

Using the makefile approach as documented by @worksofliam may have been more work to specify each object, which the bob approach handles much better, but at the same time, bob seems to be trading the vagaries of makefiles for a series of assumptions the user *must* know for even the most basic build to succeed.

**Comment by edmundreinhardt** [comment]
@TongkunZhang can you address the question of whether compile supports lowercase names.  I was under the impression that it does!

**Comment by zkarj735** [comment]
I actually changed all my source files to upper case in an effort to move around the issue and this gave exactly the same error, including listing a lower case file name (but *not* the extension).

However, in recreating the issue just now, having in the interim closed down my VSCode, that error no longer occurs, so the original may have been spurious.

For the latest test I tried using `compile` (all prior efforts were `build`) The current configs and results for `compile`.
```
{
    "version": "0.0.1",
    "description": "Alerting framework",
    "objlib": "&BUILDLIB",
    "curlib": "&BUILDLIB",
    "preUsrlibl": "&BUILDLIB"
}
```
```
      {
          "command": "err=*EVENTF /QOpenSys/pkgs/bin/makei compile -f &BASENAME -e BUILDLIB=&CURLIB",
          "deployFirst": true,
          "environment": "pase",
          "extensions": [
              "GLOBAL"
          ],
          "name": "Bob Compile"
      }
```
```
CMDs := DSPALT.CMD
DSPFs := FMDDSPALTD.FILE
MODULEs := FMRDSPALTD.MODULE
PGMs := FMRDSPALTD.PGM
PNLGRPs := FMHDSPALT.PNLGRP

DSPALT.CMD: DSPALT.CMDSRC
DSPALT.CMD: private PGM := FMRALTSND
DSPALT.CMD: private HLPPNLGRP := FMHDSPALT
FMDDSPALTD.FILE: FMDDSPALTD.DSPF
FMRDSPALTD.MODULE: FMRDSPALTD.SQLRPGLE FMDDSPALTD.FILE
FMRDSPALTD.PGM: FMRDSPALTD.ILEPGM FMRDSPALTD.MODULE
FMHDSPALT.PNLGRP: FMHDSPALT.PNLGRPSRC
```
And the result.
```
Current library: DEMOTEST
Library list: QTEMP DAGSW DAGDTA QGPL TAATOOL IOMSDTA
Commands:
		err=*EVENTF /QOpenSys/pkgs/bin/makei compile -f FMDDSPALTD.DSPF -e BUILDLIB=DEMOTEST

Set variable <BUILDLIB> to 'DEMOTEST'
> /QOpenSys/pkgs/bin/make -k BUILDVARSMKPATH="/tmp/tmpy1rphe4i" -k BOB="/QOpenSys/pkgs/lib/bob" -f "/QOpenSys/pkgs/lib/bob/mk/Makefile" FMDDSPALTD.FILE
=== Creating DSPF [FMDDSPALTD.DSPF]
/QOpenSys/pkgs/lib/bob/scripts/crtfrmstmf -f /home/ajenks/ibmi-alert-framework/FMDDSPALTD.DSPF -o FMDDSPALTD -l DEMOTEST -c CRTDSPF -p "ENHDSP(*YES) RSTDSP(*YES) DFRWRT(*YES) AUT() OPTION(*EVENTF *SRC *LIST) TEXT()"
✕ Failed to create FMDDSPALTD.FILE!

CPFA0A9: Object not found.  Object is /QSYS.LIB/DEMOTEST.LIB/EVFEVENT.FILE/FMDDSPALTD.MBR.
CPFA097: Object not copied.  Object is /QSYS.LIB/DEMOTEST.LIB/EVFEVENT.FILE/FMDDSPALTD.MBR.
make: *** [/QOpenSys/pkgs/lib/bob/mk/Makefile:67: FMDDSPALTD.FILE] Error 255
Objects:             1 failed 0 succeed 1 total
 > Failed objects:    FMDDSPALTD.FILE
Build Completed!

Fetching errors from DEMOTEST/FMDDSPALTD.
```
I don't think authority is an issue as I had previously used the raw makefile approach and completed a full build from VSCode.

**Comment by edmundreinhardt** [comment]
@worksofliam 

> This gets around the errors, but the examples/documentation need improving to state this.
> 
> It means switching between test and production builds/compiles is more fiddly than I was hoping. I had a choice of actions for this when using raw makefiles, as the variable was simply set per action.
> 
> Also, your use of `-f &BASENAME` fails with lower case source file names. I like the idea of keeping file names lower case as it makes it much easier to distinguish them from object names in the Rules file.
> 
> Using the makefile approach as documented by @worksofliam may have been more work to specify each object, which the bob approach handles much better, but at the same time, bob seems to be trading the vagaries of makefiles for a series of assumptions the user _must_ know for even the most basic build to succeed.

@worksofliam Liam, I was just wondering about your take on this?

**Comment by edmundreinhardt** [comment]
reproduced with your github, now investigating...

**Comment by edmundreinhardt** [comment]
![image](https://user-images.githubusercontent.com/11184579/190530319-951876ec-fae1-454b-bf68-8a7db956bd6d.png)
Strangely, when run from makei the crtfrmstmf command fails, but when I copy and paste it, it runs fine.    There must be some environmental difference.  Glad I am able to reproduce on my local machine.

**Comment by edmundreinhardt** [comment]
When I looking into .logs/output.log I see that the B is mistaken as a library to add to library list
```>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>  CHGCURLIB CURLIB(DEMOTEST)
>  ADDLIBLE LIB(B) POSITION(*FIRST)
[FAILED]  ADDLIBLE LIB(B) POSITION(*FIRST)
Traceback (most recent call last):
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db_dbi.py", line 1205, in _callproc_helper
    result = ibm_db.callproc(self.conn_handler, procname,parameters)
Exception: Statement Execute Failed: Trigger program or external routine detected an error. SQLSTATE=38501 SQLCODE=-443

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/QOpenSys/pkgs/lib/bob/scripts/crtfrmstmf", line 374, in <module>
    cli()
  File "/QOpenSys/pkgs/lib/bob/scripts/crtfrmstmf", line 269, in cli
    success = handle.run()
  File "/QOpenSys/pkgs/lib/bob/scripts/crtfrmstmf", line 76, in run
    self.setupEnv()
  File "/QOpenSys/pkgs/lib/bob/scripts/crtfrmstmf", line 120, in setupEnv
    self.job.run_cl(f"ADDLIBLE LIB({libl}) POSITION(*FIRST)", log=True)
  File "/QOpenSys/pkgs/lib/bob/makei/ibm_job.py", line 36, in run_cl
    cursor.callproc("qsys2.qcmdexc", [cmd])
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db_dbi.py", line 1232, in callproc
    result = self._callproc_helper(procname, parameters)
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db_dbi.py", line 1208, in _callproc_helper
    raise self.messages[-1]
ibm_db_dbi.OperationalError: ibm_db_dbi::OperationalError: Statement Execute Failed: Trigger program or external routine detected an error. SQLSTATE=38501 SQLCODE=-443
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>  CHGCURLIB CURLIB(DEMOTEST)
>  ADDLIBLE LIB(B) POSITION(*FIRST)
[FAILED]  ADDLIBLE LIB(B) POSITION(*FIRST)
Traceback (most recent call last):
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db_dbi.py", line 1205, in _callproc_helper
    result = ibm_db.callproc(self.conn_handler, procname,parameters)
Exception: Statement Execute Failed: Trigger program or external routine detected an error. SQLSTATE=38501 SQLCODE=-443

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/QOpenSys/pkgs/lib/bob/scripts/crtfrmstmf", line 374, in <module>
    cli()
  File "/QOpenSys/pkgs/lib/bob/scripts/crtfrmstmf", line 269, in cli
    success = handle.run()
  File "/QOpenSys/pkgs/lib/bob/scripts/crtfrmstmf", line 76, in run
    self.setupEnv()
  File "/QOpenSys/pkgs/lib/bob/scripts/crtfrmstmf", line 120, in setupEnv
    self.job.run_cl(f"ADDLIBLE LIB({libl}) POSITION(*FIRST)", log=True)
  File "/QOpenSys/pkgs/lib/bob/makei/ibm_job.py", line 36, in run_cl
    cursor.callproc("qsys2.qcmdexc", [cmd])
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db_dbi.py", line 1232, in callproc
    result = self._callproc_helper(procname, parameters)
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db_dbi.py", line 1208, in _callproc_helper
    raise self.messages[-1]
ibm_db_dbi.OperationalError: ibm_db_dbi::OperationalError: Statement Execute Failed: Trigger program or external routine detected an error. SQLSTATE=38501 SQLCODE=-443
```

**Comment by edmundreinhardt** [comment]
So I adjusted your iproj.json to 
```
{
    "version": "0.0.1",
    "description": "Alerting framework",
    "curlib": "&BUILDLIB"
}
```
and now I get
![image](https://user-images.githubusercontent.com/11184579/190531416-044ea5da-1fc6-477c-a1b0-7dda609320ee.png)

**Comment by edmundreinhardt** [comment]
@zkarj735  Alister, you should be able to make progress after removing the PREUSRLIBL from iproj.json
@TongkunZhang 
I don't understand why the original iproj.json doesn't work.  I will leave this issue open until you can get this iproj.json working
```
{
    "version": "0.0.1",
    "description": "Alerting framework",
    "objlib": "&BUILDLIB",
    "curlib": "&BUILDLIB",
    "preUsrlibl": "&BUILDLIB"
}
```

**Comment by zkarj735** [comment]
Thanks, and I can confirm with the same change my build now succeeds, and even with the `objlib` left in. So I assume the `B` coming from the `preUsrlibl`?  I only put that in as an attempt to get around issues (possibly this one, possibly one of the other ones). I must have cured that elsewhere and left myself with the `preUsrlibl` as a time bomb.

Thanks for persisting with this, I have a successful build now. However I now have the curious situation of `iproj.json` having  `"curlib": "&BUILDLIB"` and `actions.json` having `BUILDLIB=&CURLIB`. If I am interpreting correctly, this is the means of setting the build library when VSCode won't honour it?

**Comment by edmundreinhardt** [comment]
> However I now have the curious situation of `iproj.json` having `"curlib": "&BUILDLIB"` and `actions.json` having `BUILDLIB=&CURLIB`. If I am interpreting correctly, this is the means of setting the build library when VSCode won't honour it?

you are interpreting correctly

**Comment by zkarj735** [comment]
It just occurred to me that this successful build must have ignored the `.ILEPGM` source, which is deliberately wrong in its command, per issue #131. I had been unable to test that due to the PREUSRLIBL issue.

**Comment by edmundreinhardt** [comment]
@zkarj735 Can I assume that you are working successfully?
I think our problem with preUsrLibl is that the value needs to be in [] because it supports a list of libraries to add
