### ISSUE TITLE
Build only sees PGM object, no others

### ISSUE THREAD

**Issue by zkarj735** [IBM/ibmi-bob#130]
I have studied the documentation and sample project and run this through with a colleague and cannot understand why this `Rules.mk` only results in the PGM object being attempted.
```
CMDs := DSPALT.CMD
DSPFs := FMDDSPALTD.FILE
MODULEs := FMRDSPALTD.MODULE
PGMs := FMRDSPALTD.PGM
PNLGRPs := FMHDSPALT.PNLGRP

DSPALT.CMD: dspalt.cmd
DSPALT.CMD: private PGM := FMRALTSND
DSPALT.CMD: private HLPPNLGRP := FMHDSPALT
FMDDSPALTD.FILE: fmddspaltd.dspf
FMRDSPALTD.MODULE: fmrdspaltd.sqlrpgle FMDDSPALTD.FILE
FMRDSPALTD.PGM: FMRDSPALTD.MODULE
FMHDSPALT.PNLGRP: fmhdspalt.pnlgrp
```
All source files are named in lower case as shown and the build library is emptied for each attempt. I have tried commenting out various entries but all that ever happens is an attempt on the PGM if that line remains active. I also noted that deliberately misspelling the object list type generates no error. E.g. `CMXs : =`.

**Comment by gcraill** [comment]
To clarify from @zkarj735 above, when we commented out all entries except the DSPF for example it did not attempt to create the DSPF.

**Comment by edmundreinhardt** [comment]
Make sure you have the latest version of Bob installed.  i.e. v 2.4.0 or latest
Before that lowercase source file names were not supported.

**Comment by beckhamrryyaann** [comment]
The latest version on the IBM i repository is 2.3.9.   Can you update the repository?

**Comment by edmundreinhardt** [comment]
First do a `yum upgrade` 
`-bash-5.1$ yum upgrade
ibmi-base                                                                                        | 3.6 kB  00:00:00
ibmi-base/primary_db                                                                             | 566 kB  00:00:01
ibmi-release                                                                                     | 2.9 kB  00:00:00
Setting up Upgrade Process
Resolving Dependencies
--> Running transaction check
---> Package bash.ppc64 0:5.1-2 will be updated
---> Package bash.ppc64 0:5.1-3 will be an update
---> Package bob.ppc64 0:2.3.10-0 will be updated
---> Package bob.ppc64 0:2.4.0-1 will be an update`

**Comment by zkarj735** [comment]
To target the upgrade (and avoid upsetting anyone with python or php upgrades they're not ready for).
```
yum upgrade ibmi-repos
yum upgrade bob
```
That left me with 2.4.0.1 and now I am getting errors about my objects, which means the problems are now my own. :-)

**Comment by edmundreinhardt** [comment]
More info
https://techchannel.com/Trends/08/2022/ibm-i-rpm-repositories

https://ibmi-oss-docs.readthedocs.io/en/latest/yum/IBM_REPOS.html
