### ISSUE TITLE
Correct way to build a PGM from MODULEs

### ISSUE THREAD

**Issue by zkarj735** [IBM/ibmi-bob#131]
This may be a failure of documentation or the sample project rather than the tool, but I am unclear on the correct approach to build a PGM object from constituent modules. 

My first assumption was to use `MYPGM.PGM: MYMODULE.MODULE` and this does seem to work, however, I was looking for a means of qualifying the module to the build library. In searching the sample project, I was surprised to find a whole load of modules in, e.g. QRPGLESRC, and no mention of any PGMs that are built from them. 

QILESRC contains a different form: `MYPGM.PGM: MYPGM.ILESRC MYMODULE.MODULE` where `MYPGM.ILESRC` contains the CL command `CRTPGM`. I tried this construct, however bob used exactly the same command it had used in the first example.

My need for qualifying the module is due to the system library list. Building a test version of a tool that is in the system library list requires careful qualification of many objects. It may be that best practice is to run a pre-command to remove that library, but that would also remove a myriad other tools. At the very least the documentation should be explicit on this behaviour if it always uses *LIBL. I note the `.ILEPGM` construct would allow this qualification, if it worked.

**Comment by edmundreinhardt** [comment]
Not that is 
`MYPGM.PGM: MPGM.ILEPGM MYMODULE.MODULE`
and not
`MYPGM.PGM: MYMODULE.ILESRC`
i.e. make sure you use the .ILEPGM file extension to specify the binding command

You are right that we need more documentation on binding with ILE.
I will add that to https://ibm.github.io/ibmi-bob/#/prepare-the-project/rules.mk
in the next little while.

But at a high level there are 2 ways to do binding from modules
If you want to compile and bind in one step then use
`MYPGM.PGM: MYPGM.PGM.RPGLE`

If you have a simple binding situation use
`FARTICLE.SRVPGM: $(d)/FARTICLE.BND ART300.MODULE ART301.MODULE FFAMILLY.SRVPGM`
where all of the information is figured out from the binder source and the dependencies.  See QSRVSRC directory of the bob-recursive-example.

If you want total control over the CRTPGM/SRVPGM call then using a `ILEPGM' or 'ILESRVPGM' files as seen in the QILESRC or 'QILESRVSRC' directories of  the bob-recursive-example

**Comment by zkarj735** [comment]
We have not, for the most part, used binding directories because we have always just manually created the PGMs or used UPDPGM. So I will revisit that approach as it seems the 'right' way to do it.

However, your described behaviour for the 'direct' method is not what we're observing.

This...
```
FMRDSPALTD.PGM: fmrdspaltd.ilepgm FMRDSPALTD.MODULE
```
...where `fmrdspaltd.ilepgm` contains this spurious command (the module is not real)...
```
CRTPGM PGM(&O/&N) MODULE(&O/BOB)
```
...produces this...
```
=== Creating program [FMRDSPALTD] from modules [FMRDSPALTD] and service programs []
crtpgm pgm(DEMOTEST/FMRDSPALTD) module(FMRDSPALTD) bndsrvpgm(*NONE) ACTGRP() USRPRF(*USER) TGTRLS() AUT() DETAIL(*EXTENDED) OPTION() STGMDL(*SNGLVL) TEXT('')
✓ FMRDSPALTD.PGM was created successfully!
```
...which is exactly the same outcome as if the rule was...
```
FMRDSPALTD.PGM: FMRDSPALTD.MODULE
```

**Comment by edmundreinhardt** [comment]
I suspect that you are not at the latest version 2.4
and therefore BOB can't find the lowercase file name fmrdspaltd.ilepgm
In 2.3.10 and earlier it transforms the target name and make is case-sensitive
In 2.4 we have extensively enhanced Bob to parse the Rules.mk and search the file system using python to generate accurate rules.

**Comment by zkarj735** [comment]
Per other issues, I have now upgraded to 2.4.0.1 and we revalidate this, however further issues have now arisen which I will report separately.
