### ISSUE TITLE
Panel Group source extension inconsistent between (documentation & example project) and actual build

### ISSUE THREAD

**Issue by zkarj735** [IBM/ibmi-bob#132]
The example project and the documentation state that `.PNLGRP` objects should have `.PNLGRP` source extension, however this resulted in an error. On changing the extension to `.PNLGRPSRC` it was compiled successfully.

**Comment by edmundreinhardt** [comment]
@TongkunZhang  this should be straightforward to fix

**Comment by edmundreinhardt** [comment]
Good catch.  i have updated the documentation and the example bob-recursive-example

Thanks for bringing this to our attention.
