### ISSUE TITLE
Bob 2.4.1 Compiling Programs includes empty INCDIR ('') on compile command

### ISSUE THREAD

**Issue by beckhamrryyaann** [IBM/ibmi-bob#149]
After updating to Bob 2.4.1 I now cannot compile any programs using the makei command.  When looking at the logs I see the compile command for my programs to include an empty string for the INCDIR compile option.  The system does not like this and causes the compile to crash.   I am seeing this on the CRTSQLRPGI, CRTBNDCL commands.   I am able to copy the compile command and paste on a green screen and remove the INCDIR option and it will compile successfully.   Why did BOB suddenly start adding this to compile command?

![image](https://user-images.githubusercontent.com/6051612/196528490-36fa47fd-cb05-44c3-a5a7-3dc4244e5267.png)

**Comment by edmundreinhardt** [comment]
This will be fixed in Bob 2.4.4 which is available as an rpm and will be available in yum soon

**Comment by beckhamrryyaann** [comment]
@edmundreinhardt can you reopen this case for 2.4.4?

the incdir does not appear to be correct:  notice it has the *NONE in quotes '*NONE'.  I don't think the quotes should be there.  If I run that command on a green screen and remove the quotes around *NONE it will compile correctly.

![image](https://user-images.githubusercontent.com/6051612/197029494-f754aaa6-39ac-454d-8f11-726a766b696f.png)
![image](https://user-images.githubusercontent.com/6051612/197029903-89aaa0a5-1772-4482-a9e3-008eade33995.png)

**Comment by edmundreinhardt** [comment]
I hear you,  as a workaround,  just set the includePath in the iproj.json to any directory
I will get a new release out soon.

**Comment by beckhamrryyaann** [comment]
will do .  Thanks!

**Comment by edmundreinhardt** [comment]
Just to clarify, with the extra quotes, which I agree are unnecessary, it still does compile cleanly does it not?
It appears that you have specified "includePath": "*none" in your iproj.json
A good workaround for now is to simply remove the attribute and you will end up with the proper INCDIR(*NONE) as the default.
I will remove the unnecessary quotes but this is not worth spinning a new release for.

**Comment by beckhamrryyaann** [comment]
From my testing, it will not compile with the extra quotes.   INCDIR('*NONE').  It will not compile.
I did not specify any values in my iproj.json file for the includePath property. It was empty just an empty array. (see below) 

I did your suggestion mentioned prior and included a valid includePath in the iproj.json to get around this issue.
In my opinion, this is a serious break that causes all program compiles to break if not using a include path forcing me to include a bogus value to workaround.   The workaround is simple enough so it may not warrant a new release.

`{
    "version": "0.0.1",
    "description": "McCreary Modern - Production Planning",
    "objlib": "&lib1",
    "curlib": "&lib1",
    "includePath": [],
    "preUsrlibl": ["&lib1"],
    "postUsrlibl": [""],
    "setIBMiEnvCmd": [],
    "repository" : ""
}`

**Comment by edmundreinhardt** [comment]
I have spent some time on resolving it but I am hitting a snag with CL compiling so I am not able to publish at this time.
What about the workaround about droping the includePath attribute from iproj.json entirely if you don't need it.

**Comment by beckhamrryyaann** [comment]
I tried that earlier today Dropping the attribute altogether and it still gave the same error.   I understand. I have a working workaround so no rush for my projects.  Sent from my iPhoneOn Oct 20, 2022, at 9:03 PM, Edmund Reinhardt ***@***.***> wrote:﻿
I have spent some time on resolving it but I am hitting a snag with CL compiling so I am not able to publish at this time.
What about the workaround about droping the includePath attribute from iproj.json entirely if you don't need it.

**Comment by edmundreinhardt** [comment]
Appreciate your understanding Ryan
I am getting up at 4 to catch a plane tomorrow and won't be back until Tuesday.
@jonnyz32 Jonathan, would you be able to take a look at this in my absence.  Once again only the CRTCLMOD is failing
If you remember it is forced to use CRTFRMSTMF to get the TGTCCSID support because the CL compilers do not support that yet.  The problem was that the relative paths in INCDIR did not work because the project root was not the current directory.  We solved by making the directories absolute, using the joblog.json path to get the project root.
For some reason this is broken again and I am out of time.
Thanks

**Comment by jonnyz32** [comment]
@edmundreinhardt Thanks, I'll try to take a look soon
