### ISSUE TITLE
MSGF source should be unique from the MSGF object type.  I.e. make it MSGFSRC

### ISSUE THREAD

**Issue by edmundreinhardt** [IBM/ibmi-bob#164]

**Comment by johnsherrill** [comment]
Just curious, what would be in the message file source? To the best of my knowledge the only way to add a message to a message file is the addmsgd command.

**Comment by edmundreinhardt** [comment]
Actually we now support the file extension being the same as the object type, which is the most intuitive, so we will keep the file extension as MSGF
