### ISSUE TITLE
Automate process of creating new bob releases 

### ISSUE THREAD

**Issue by jonnyz32** [IBM/ibmi-bob#168]
We should have a script that we can run that will create a new bob release

**Comment by TongkunZhang** [comment]
FYI https://github.com/TongkunZhang/bob-release-tools

**Comment by jonnyz32** [comment]
Thanks!

**Comment by edmundreinhardt** [comment]
This is all documented in https://ibm.github.io/ibmi-bob/#/contributing/getting-started
