### ISSUE TITLE
Configure the .bash_profile

### ISSUE THREAD

**Issue by HenryMiller** [IBM/ibmi-bob#171]
Hello,
I've added .bash_profile file to my home directory.
Signing in via ssh raises the error below:

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
(base) MacBookPro16-Giovanni:m11 Giovanni$ ssh xxxxxxx@as400
xxxxxx@as400's password: 
): No such file or directoryC_ALL: cannot change locale (IT_IT.UTF-8

I did try EN_US.UTF-8 as well but without success, QSYSLOCALE library contains  both of them .

<img width="574" alt="image" src="https://user-images.githubusercontent.com/1829995/203266173-aaf4db26-d597-4c92-b72c-606fad672a24.png">

Best regards,
Giovanni

**Comment by edmundreinhardt** [comment]
The LC_ALL is not really required. You can remove that line.

**Comment by edmundreinhardt** [comment]
I will update the docs and remove that line. 
This setting might have some impact on C and COBOL compilers and if you are using them then you will have to make sure that you use the CRTLOCALE command to create the locale that you are targeting.
