### ISSUE TITLE
Object creation for QILESRVSRC pseudo source object reported as successful when not.

### ISSUE THREAD

**Issue by JDubbTX** [IBM/ibmi-bob#176]
I have some QILESRVSRC psuedo source with a bug in it.  When I run 'makei build', the output says the object was created successfully, and is not listed in the list of failed objects.

Unfortunately the object didn't exist, despite the success message.  Upon further exploration, there were messages in the job log that do in fact indicate a failed build, which led me to the discovery of the bug in my psuedo source cl command.

Here is a the QSRVSRC source with the bug:
![image](https://user-images.githubusercontent.com/56802156/204850562-0e91491b-6215-461b-95ab-e37893387b3c.png)

And a basic rule for it:
![image](https://user-images.githubusercontent.com/56802156/204850744-bc0883fb-4853-4984-a589-e7bcb1288681.png)

Here is the success message in the output (you can actually see the bug with the missing quote):
![image](https://user-images.githubusercontent.com/56802156/204843273-4c5575c3-40e1-471e-a276-5c48e3e0e308.png)

Object not included in the list of failures:
![image](https://user-images.githubusercontent.com/56802156/204843437-8836518b-909b-4091-a649-cc1a78de8e3d.png)

Here are the relevant messages in the job log:
![image](https://user-images.githubusercontent.com/56802156/204843044-e5beeee8-7273-4048-b0aa-398e926f1ae7.png)

**Comment by edmundreinhardt** [comment]
Thanks for the thorough investigation.  We will look at this when we get a chance.  I suspect the script/launch is not setting the return code.  I see that it is trying to use $? to get the return code from the cl bash command
```
cl "$cmd"
exitCode=$?
echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
echo
"$SCRIPT_DIR"/getJobLog "$cmd" "$timestamp" "$jobid" -f "$joblog_json"
exit $exitCode
```

**Comment by irfanshar** [comment]
Fixed in https://github.com/IBM/ibmi-bob/pull/317
