### ISSUE TITLE
changed IFS file not recognized, compile not done.

### ISSUE THREAD

**Issue by JDubbTX** [IBM/ibmi-bob#179]
when running 'makei build' this program is built/compiled fine.
when I change the source locally in vscode, save it, deploy it with vscode, then initiate a Bob compile, output shows that there is nothing to be done.  I would expect that the compile would be done since I changed the source and saved it locally, then deployed it.

Object description shows it was created 12/6/22 at 14:39:46:
![image](https://user-images.githubusercontent.com/56802156/206077901-294b8546-9e74-4707-993c-a24064c297b8.png)

IFS file attributes show create date BEFORE object create date, but change date AFTER object create date:
![image](https://user-images.githubusercontent.com/56802156/206078156-3cfdd0d4-56b1-4c51-86b6-8fd2f4a2d4d9.png)

I suspect BOB / Make is going by the IFS file creation date/time, not the change date/time.  When deploying with Code for IBM i / VSCODE, only the change date/time is updated on the IFS file, so this would be incorrect.

Here is the output of the command when initiated from VSCODE, when changed locally, deployed, then compiled with Bob:
```
Current library: RDGJWEIRIC
Library list: RDGJWEIRIC QGPL QTEMP GNFGEND GNFGEN GNFITGCSTM GNFITGCORE GNFQUACSTM GNFQUACORE GNFGENPI GNFGENP GNFDTAPI GNFDTAP GNFPGMP SEQUEL GNFDTAG11 ECNCT ECIDEV
Commands:
		OPT=*EVENTF BUILDLIB=RDGJWEIRIC /QOpenSys/pkgs/bin/makei compile -f sls1upc.pgm.clle

targets: SLS1UPC.PGM
> /QOpenSys/pkgs/bin/make -k BUILDVARSMKPATH="/tmp/tmpppo8ujuw" -k BOB="/QOpenSys/pkgs/lib/bob" -f "/QOpenSys/pkgs/lib/bob/mk/Makefile" SLS1UPC.PGM
CPF2103: Library ECNCT already exists in library list.CPF2103: Library RDGJWEIRIC already exists in library list.
CPF2103: Library ECNCT already exists in library list.
CPF2103: Library RDGJWEIRIC already exists in library list.
CPF2103: Library ECNCT already exists in library list.
CPF2103: Library RDGJWEIRIC already exists in library list.
CPF2103: Library ECNCT already exists in library list.
CPF2103: Library RDGJWEIRIC already exists in library list.
CPF2103: Library ECNCT already exists in library list.
CPF2103: Library RDGJWEIRIC already exists in library list.
CPF2103: Library ECNCT already exists in library list.
CPF2103: Library RDGJWEIRIC already exists in library list.
CPF2103: Library ECNCT already exists in library list.
CPF2103: Library RDGJWEIRIC already exists in library list.
CPF2103: Library ECNCT already exists in library list.
CPF2103: Library RDGJWEIRIC already exists in library list.
CPF2103: Library ECNCT already exists in library list.
CPF2103: Library RDGJWEIRIC already exists in library list.
CPF2103: Library ECNCT already exists in library list.
CPF2103: Library RDGJWEIRIC already exists in library list.
CPF2103: Library ECNCT already exists in library list.
CPF2103: Library RDGJWEIRIC already exists in library list.
CPF2103: Library ECNCT already exists in library list.
CPF2103: Library RDGJWEIRIC already exists in library list.
make: Nothing to be done for '/QSYS.LIB/RDGJWEIRIC.LIB/SLS1UPC.PGM'.
Objects:             0 failed 0 succeed 0 total
Build Completed!

Fetching errors from RDGJWEIRIC/sls1upc.
Failed to download a file after Action: No such file
```
The output above is what shows up in IBM i Output in VSCODE, but when I run the same is the same when i run the samve command 'makei compile -f /qcllesrc/sls1upc.pgm.clle' in a PASE shell, the output is similar:
```
~/pocs/ibmistatementswithbob$ makei compile -f /qcllesrc/sls1upc.pgm.clle
targets: SLS1UPC.PGM
> /QOpenSys/pkgs/bin/make -k BUILDVARSMKPATH="/tmp/tmpumjup9jh" -k BOB="/QOpenSys/pkgs/lib/bob" -f "/QOpenSys/pkgs/lib/bob/mk/Makefile" SLS1UPC.PGM
make: Nothing to be done for '/QSYS.LIB/RDGJWEIRIC.LIB/SLS1UPC.PGM'.
Objects:             0 failed 0 succeed 0 total
Build Completed!
~/pocs/ibmistatementswithbob$ 
```
I should also not that when this happens, VSCODE gives a notification that the build was successful.
![image](https://user-images.githubusercontent.com/56802156/206078919-e9d7977e-b9cf-46be-9259-75bc4a4b7370.png)

**Comment by edmundreinhardt** [comment]
@TongkunZhang will investigate, but we thing that gmake should work on the modify date not creation date.
Is it possible that you have another copy of the object higher up in your library list?

The build is considered successful. Since no commands failed.


Looking at your command:
```
makei compile -f /qcllesrc/sls1upc.pgm.clle
```
the path is to source in the `/qcllesrc` directory in the root. Did you not mean relative to your `ibmistatementswithbob` directory?

**Comment by edmundreinhardt** [comment]
But this does not explain your behaviour in VSCode.

**Comment by JDubbTX** [comment]
I tried it both ways in the pase shell.
I am running a command that sets a library list in iproj.json:
![image](https://user-images.githubusercontent.com/56802156/206546783-2b1f9011-126a-4687-83cf-1e045a589258.png)

ACMSLIBL command is what our current source / object management solution - Aldon lmi - uses, so my intention in doing it this way was to be consistent with our build process library list.  This library list WILL include multiple copies of the object, but the development version should be at the top of the list.

Here is what happens when I do a WRKOBJ after setting the library list with that command:
![image](https://user-images.githubusercontent.com/56802156/206547522-066abdae-5451-40f1-92cb-a1e88bf71e7d.png)

So attributes should be taken from the object in RDGJWEIRIC.  Perhaps it is taking attributes from the one in GNFPGMP, which would be incorrect?  Even so, that object is much older.

There are also copies of QCLLESRC in many libraries in the library list, with RDGJWEIRIC is at the top.  That particular member is not in RDGJWEIRIC, but it does reside in QCLLESRC files lower in the library list which are older, and would be older that the object sitting in RDGJWEIRIC.  But that shouldn't matter, since the source is in IFS.

**Comment by edmundreinhardt** [comment]
I looked at it and I think you have the library list correct, that is not the problem

**Comment by JDubbTX** [comment]
I think a related issue is that when I run 'makei build' everything is recompiled, whether I have changed the source or not.  It should only build changed sources, correct?

**Comment by worksofliam** [comment]
@JDubbTX Reached out to you to see if you want to connect and recreate this together.

**Comment by edmundreinhardt** [comment]
Are you still having trouble with this?

**Comment by JDubbTX** [comment]
Hi Edmund - I have been testing bob again in my free time using pub400 for a blog article I plan to write, and it seems to work perfectly there.  I was having issues before on the development partition where I work and alas I have not had the time to retest it there.  I'll close this issue for now since I am having no issues on PUB400.

**Comment by edmundreinhardt** [comment]
might be a timing issue on that partition.  Will close for now
