### ISSUE TITLE
Support OPTION parameter for Binder Language rules

### ISSUE THREAD

**Issue by JDubbTX** [IBM/ibmi-bob#180]
I have several Service programs that require OPTION(*DUPPROC) when running the CRTSRVPGM command.  Please start supporting this parameter for binder language source rule definitions.

**Comment by edmundreinhardt** [comment]
We will try to provide private variable overrides fro OPTION on CRTSRVPGM just like we do for other compile commands (see the top of `mk/def_rules.mk`
