### ISSUE TITLE
Project level flag to build an entire project for a target debug level.

### ISSUE THREAD

**Issue by sbestgen** [IBM/ibmi-bob#203]
My project has a need to create two different targets from the same source: MYDBGLIB which builds all objects with a desired debug level (source) and MYOPTLIB, which builds all objects with DEBUG(*NONE) and then specifies various optimization options on target parts.  Instead of having to override the DBGVIEW as a private compile parm on each part, and have a different rules.mk for the DBGLIB build vs the OPTLIB build, it would be great to have something more global (perhaps in the iproj.json or an optional parm on the makei build command) to set this option globally for the entire build.

**Comment by johnsherrill** [comment]
DBGVIEW in the def_rules.mk currently is set to DBGVIEW := *ALL. You could set it to something like this. DBGVIEW := $(BUILD_DEBUG).  This will cause DBGVIEW to be set to the value of the environment variable BUILD_DEBUG. So before running you debug build you set the environment variable with either a export (in a script) or  ADDENVVAR or CHGENVVAR. For example export BUILD_DEBUG="*SOURCE" or ADDENVVAR ENVVAR('BUILD_DEBUG') VALUE'*SOURCE').

**Comment by sbestgen** [comment]
Nice solution - thx for the tip.

**Comment by sbestgen** [comment]
I did try this with my project, but I'm not having luck getting the environment variable set in iproj.json to show up in def_rules.mk.  Maybe I've missed something .. 
![image](https://user-images.githubusercontent.com/107139127/220426995-eaee7770-aec6-4359-96d8-57c8192b6a0d.png)

**Comment by johnsherrill** [comment]
You may need to LEVEL(*SYS) to the addenvvar command. Depending on many things the environment variable may not be passed as job level one.

**Comment by sbestgen** [comment]
A good theory .. I tried that as well with no luck.  At least I can verify the envirnoment variable value did get detected and the command ran. 
![image](https://user-images.githubusercontent.com/107139127/220454598-3e5de1be-39b0-4c77-98e3-21f6da37346a.png)

**Comment by johnsherrill** [comment]
Maybe Edmund Reinhardt or Tongkun Zhang can comment, as they know the current setup much better than I.

**Comment by edmundreinhardt** [comment]
Will investigate

**Comment by edmundreinhardt** [comment]
Figuring this out will also help address https://github.com/IBM/ibmi-bob/issues/208
