### ISSUE TITLE
Statement failed _backup_and_delete_objs in CrtFrmStmf.py

### ISSUE THREAD

**Issue by beckhamrryyaann** [IBM/ibmi-bob#207]
I am running BOB 2.4.9.

I was attempting to build my project and came across failures when trying to compile my CL programs.  I have included a screenshot of the error to help.  
From glancing over the error log, it may be because the CL command for SAVOBJ has an error in it.  It appears several command options run together with no spaces to seperate them (see where I circled in red).
I have 3 CL programs in my project and they all failed with same error.  Everything else worked as expected.

![image](https://user-images.githubusercontent.com/6051612/224719695-3c26c697-e638-440d-ad5a-43c9941a0716.png)

**Comment by edmundreinhardt** [comment]
This is now fixed in BOB v.2.4.11
