### ISSUE TITLE
Overriding the OBJLIB and TGTCCSID in subdirectory not working 

### ISSUE THREAD

**Issue by ScottA678** [IBM/ibmi-bob#220]
When using an .ibmi.json setting at a subdirectory to override the project OBJLIB

- Physical files are built in the project level OBJLIB
- Logical files are built in the subdirectory OBJLIB

**Comment by edmundreinhardt** [comment]
Interesting, I will have to investigate.

**Comment by edmundreinhardt** [comment]
Found the problem and integrating a fix

**Comment by edmundreinhardt** [comment]
the same problem affects overriding TGTCCSID
