### ISSUE TITLE
Support for rules to run system commands

### ISSUE THREAD

**Issue by sbestgen** [IBM/ibmi-bob#223]
Add support to run various miscellaneous system commands not covered by existing object types.   For example:  

CRTSBSD.FILE:dummy.pf
	system -i "CRTSBSD SBSD(BATCHWL/BATCHSBSD) POOLS((1 *SHRPOOL3 *N *MB))"
CHGSBSD.FILE:dummy.pf
	system -i "CHGSBSD SBSD(BATCHWL/BATCHSBSD) POOLS((3 8000 999 *MB))"  
CRTJOBQ.FILE:dummy.pf
	system -i "CRTJOBQ JOBQ(BATCHWL/BWLJOBQ)"  
CRTJOBD.FILE:dummy.pf	
	system -i "CRTJOBD JOBD(BATCHWL/BWLJOBD) JOBQ(BATCHWL/BWLJOBQ) LOG(4 40 *MSG)"
ADDJOBQE.FILE:dummy.pf	
	system -i "ADDJOBQE SBSD(BATCHWL/BATCHSBSD) JOBQ(BATCHWL/BWLJOBQ) MAXACT(*NOMAX) SEQNBR(15)"
CRTCLS.FILE:dummy.pf	
	system -i "CRTCLS CLS(BATCHWL/BWLCLASS) RUNPTY(30) TIMESLICE(5000)"  
ADDRTGE1.FILE:dummy.pf	
	system -i "ADDRTGE SBSD(BATCHWL/BATCHSBSD) SEQNBR(9999) CMPVAL(*ANY) PGM(QSYS/QCMD) CLS(BATCHWL/BWLCLASS) POOLID(3)"

**Comment by sbestgen** [comment]
I did have tabs, but after this comment I tried with tabs, spaces, and no spaces.   Can't seem to get it to run (haven't looked too deeply, working on other tasks at the moment).

**Comment by edmundreinhardt** [comment]
let me investigate

**Comment by edmundreinhardt** [comment]
OK I got it working with a few tweaks on your Rules.mk
```
-bash-5.1$ makei b -t CRTSBSD.FILE -e lib1=BOBBUILD
Set variable <lib1> to 'BOBBUILD'
> /QOpenSys/pkgs/bin/make -k BUILDVARSMKPATH="/tmp/tmppyno8ixq" -k BOB="/QOpenSys/pkgs/lib/bob" -f "/QOpenSys/pkgs/lib/bob/src/mk/Makefile" CRTSBSD.FILE
=== Creating [CRTSBSD.FILE] from custom recipe
system -i "CRTSBSD SBSD(BATCHWL/BATCHSBSD) POOLS((1 *SHRPOOL3 *N *MB))"
CPD000D: Command *LIBL/CRTSBSD not safe for a multithreaded job.
CPD9801: Library BATCHWL not found.
CPF1696: Subsystem description BATCHSBSD not created.
make: *** [/home/REINHARD/bob-recursive-example/susan/.Rules.mk.build:7: CRTSBSD.FILE] Error 255
Objects:             0 failed 0 succeed 0 total
Build Completed!
```

I changed it to 
```
CRTSBSD.FILE: SAMREF.FILE
	system -i "CRTSBSD SBSD(BATCHWL/BATCHSBSD) POOLS((1 *SHRPOOL3 *N *MB))"
```
Notice that I had to give it a real file that already exists
I put a space after the colon of the target and a tab before the system command

**Comment by edmundreinhardt** [comment]
We will keep this issue because you shouldn't have to make a dummy source

**Comment by edmundreinhardt** [comment]
https://vscode.dev/github/IBM/ibmi-bob/blob/b816e8bd912fb37a78896a24e01e88de2559fc60/src/makei/rules_mk.py#L120
Problem was address with this regex to parse a target line with no dependencies, but now it breaks if line is followed by a space
```
target: dep<\n>
<space><\n>
```
