### ISSUE TITLE
What does bob-path represent?

### ISSUE THREAD

**Issue by SJLennon** [IBM/ibmi-bob#237]
I assumed it was the path to the project, but apparently not...

I have the `bob-recursive-example` project in the IFS.as  `/home/LENNONS/bob-recursive-example`.
My home and current directory is `/home/LENNONS`
Running build in PuTTY using bob-path quits immediately because it can't find `iprod.json`:
```
 [~]$ pwd
/home/LENNONS
 [~]$ makei b -d  QDTASRC --bob-path /home/LENNONS/bob-recursive-example
iproj.json not found!
 [~]$
```
I know I can make /home/LENNONS/bob-recursive-example the current directory first, but what does bob-path represent?

**Comment by edmundreinhardt** [comment]
You should normally not have to set the `bob-path`.  It is the path into which BOB itself is installed.
So when you `yum install bob` it gets placed into `/QOpenSys/pkgs/bob`

Yes you should make `/home/LENNONS/bob-recursive-example` before running your `makei b -d QDTASRC`
