### ISSUE TITLE
Shouldn't <file> and <library> be defaulted to UPPERCASE for cvtsrcpf?

### ISSUE THREAD

**Issue by rogersonra** [IBM/ibmi-bob#238]
I was trying to use "makei cvtsrcpf qrpglesrc bob_test" and I get the message "0 source members found." I confirmed that bob_test/qrpglesrc does have members.

I finally got this to work when I changed the command to "makei cvtsrcpf QRPGLESRC BOB_TEST". I believe the <file> and <library> parameters are referring to the library and src-pf on the IBM i so shouldn't these always be converted to uppercase?

**Comment by edmundreinhardt** [comment]
Thank you for pointing out this bug and thank you ever more for identifying the fix.  The fix is committed and I will start getting a yum update going tomorrow

**Comment by rogersonra** [comment]
It sounds like there may be a fix for the deployment always creating the
objects under qsecofr.

Thanks for the help on Friday.

Rob

**Comment by edmundreinhardt** [comment]
Now fixed in `yum install bob` when you get 2.4.15   or later
