### ISSUE TITLE
Bob branch configuration

### ISSUE THREAD

**Issue by pabloto** [IBM/ibmi-bob#239]
Hi,

I'm working in local with visual studio code, I want than the main/master branch contains the production source of my project, so when I have to develop a new function, or correct a bug I want to create a new branch, and my wish is to compile on a different library on my system bound to this specific branch. My desire is to configure it without change manually the current library.

How can I configure this with bob?

Many thanks.

**Comment by edmundreinhardt** [comment]
Absolutely!
BOB is designed to be very configurable.  That is why your `curlib` should be set to a variable.  Then you set the value of that variable to whatever library you want to build your objects into.
