### ISSUE TITLE
Makei failing to set objlib

### ISSUE THREAD

**Issue by rogersonra** [IBM/ibmi-bob#240]
When I try and create a simple RPGLE program with one file (which exists) I the following in my terminal

rrogerson@KT24002C:~/dcutils$ makei compile -f DC250.PGM.RPGLE -e lib1=DCUTILS
Set variable <lib1> to 'DCUTILS'
targets: DC250.PGM

/QOpenSys/pkgs/bin/make -k BUILDVARSMKPATH="/tmp/tmplblq_eyb" -k BOB="/QOpenSys/pkgs/lib/bob" -f "/QOpenSys/pkgs/lib/bob/src/mk/Makefile" DC250.PGM
=== Create Bound RPG Program [DC250]
CRTBNDRPG srcstmf('/home/RROGERSON/DCUtils/QRPGLESRC/DC250.PGM.RPGLE') PGM(/DC250) DBGVIEW(ALL) TGTCCSID(JOB) OPTION(*EVENTF) TEXT('') INCDIR('QRPGLEREF')
✕ Failed to create DC250.PGM!

CPFA0DB: Object not a QSYS.LIB object. Object is /EVFEVENT.FILE/DC250.MBR.
CPFA097: Object not copied. Object is /EVFEVENT.FILE/DC250.MBR.
make: *** [/QOpenSys/pkgs/lib/bob/src/mk/Makefile:67: DC250.PGM] Error 255
Objects: 1 failed 0 succeed 1 total

Failed objects: DC250.PGM
Build Completed!

Note the PGM parameter on the CRTBNDRPG command. Why is this not being set?

**Comment by edmundreinhardt** [comment]
Hi Rob
Are you still having this problem.
I think you neglected to set the `objlib` or `curlib` in your `iproj.json` to be `lib1`
