### ISSUE TITLE
Program built on every build, source not changed.  Data area not building

### ISSUE THREAD

**Issue by JDubbTX** [IBM/ibmi-bob#244]
I've tested this on PUB400.com as well as my work IBM i development lpar and see the same behavior.

my local lpar has Bob 2.4.15-1 installed
pub400.com currently has Bob 2.4.13 installed

I'm experiencing this with a small project that contains only 1 CL program and 1 Data area.

When I run 'makei b' the CL program is built every time, but the data area is never created.

To reproduce:
1) Clone this repo to an IFS folder:  [https://github.com/JDubbTX/testbasherrorcodes](https://github.com/JDubbTX/testbasherrorcodes) 
2) cd into the project folder
3) modify iproj.json to have the correct libraries
4) run makei b - The CL program is built but the data area is not
5) run makei b again - The CL program is built again and the data area is still not

Since I cloned the source but never modified it, I would expect the CL program to build only on the first 'makei b'.  I don't know why its not picking up the data area in qdtasrc either, perhaps someone can take a look at my rules.mk files and tell me if I've done something wrong

**Comment by edmundreinhardt** [comment]
@JDubbTX sorry for the delay
We will try to look at this now.

**Comment by irfanshar** [comment]
Hi, @JDubbTX , apologies for the delay. We have addressed the issue in v2.4.16. In this change, all target objects built from source DTAARA files should now also have the extension DTAARA (instead of simply DTA). 

For example, after upgrading your version of ibmi-bob, your updated qdtasrc/Rules.mk should be 
```TESTERRCD.DTAARA: TESTERRCD.DTAARA```

**Comment by irfanshar** [comment]
Hi @JDubbTX sorry about the delay, the way to resolve your issue is to have your target object uppercase. So for your qcllesrc/Rules.mk, it would look like the following. 

```TESTBASHEC.PGM: testbashec.pgm.clle```

Pending our next release, we address this issue so your target object can be in lowercase or uppercase.
