### ISSUE TITLE
To support new joblog - need to include target object in joblog.json

### ISSUE THREAD

**Issue by edmundreinhardt** [IBM/ibmi-bob#248]

**Comment by sebjulliand** [comment]
Ideally, we should add `name`, `sourceType` and `objectType` on each first level entry, in the joblog if it's a compilation entry.

**Comment by edmundreinhardt** [comment]
sure, just give me an example so we can code to it.

**Comment by edmundreinhardt** [comment]
@sebjulliand 
Just thinking it through from a BOB/IFS perspective, the source file name might be very different from the target object name.  In this case it might be better to have target object name (with type as file extenstion) and source name with externsion to communicate all attributes clearly. i.e.
```json
{
"object": "MYPGM.PGM"
"source": "myDescriptiveName.pgm.rpgle"
"output": "MYPGM.splf"
"failed" false
}
```

**Comment by sebjulliand** [comment]
@edmundreinhardt that's fine, let's go with this!
