### ISSUE TITLE
Split output.log into separate targetobject.log files and reference them in under the command in the   joblog.json

### ISSUE THREAD

**Issue by edmundreinhardt** [IBM/ibmi-bob#249]
@sebjulliand Seb, please tell us the exact format

**Comment by sebjulliand** [comment]
I'd say a new `output` field on each first level item in joblog.json.
The file name should be enough, assuming it's always located in the project's `.logs` folder.

**Comment by sebjulliand** [comment]
@edmundreinhardt : see https://github.com/IBM/ibmi-bob/issues/248#issuecomment-1680607062
