### ISSUE TITLE
cvtsrcpf should generate the version attribute in the .ibmi.json file

### ISSUE THREAD

**Issue by edmundreinhardt** [IBM/ibmi-bob#256]
To avoid the linter complaining about the file

**Comment by edmundreinhardt** [comment]
Or even easier, make the .ibmi.json version attribute optional in vscode-ibmi-project-explorer

**Comment by irfanshar** [comment]
The version attribute is now optional in vscode-ibmi-project-explorer https://github.com/IBM/vscode-ibmi-projectexplorer/blob/main/schema/ibmi.schema.json#L35

Are we good to close this issue? @edmundreinhardt
