### ISSUE TITLE
Struggling with getting BOB to work from VS code Code for IBM i

### ISSUE THREAD

**Issue by arco400** [IBM/ibmi-bob#260]
I find myself struggling with getting BOB to work from VS code Code for IBM i.

Everytime I try to build from the test projects (for example Liams ibmi-company_system project) I'm getting an error complaining about the system PATH.
However, I have checked the path environment variable dozens of times, and followed the advises in the documentation. 
My PASE shell is bash, and my path variable in PASE is "/QOpenSys/pkgs/bin:/QOpenSys/pkgs/bin:/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin" which I believe is (over)correct.

Running the bob-recursive-example within PASE runs fluent, building with Liams GMAKE examples runs also very well. But with BOB from Code for IBM i I'm constantly getting the error below. 

Any ideas how this can be solved? 

Thanks, Arco

Error message:

Commands:
	/QOpenSys/pkgs/bin/makei build -e verlibcsy=CMKASOBJ

It looks like /QOpenSys/pkgs/bin/ is not currently in your system PATH. 
This means that programs and tools installed in this directory may not be 
easily accessible from the command line.

To add /QOpenSys/pkgs/bin/ to your system PATH (if it is not already present), 
use the following command:

export PATH=$PATH:/QOpenSys/pkgs/bin

You can also add this command to your shell profile file 
(e.g. ~/.bashrc or ~/.bash_profile) to make the change permanent.

python3 is not installed or not in your system PATH.

*EVENTF not found in command string. Not fetching errors for CMKASOBJ/DEPTS.
Failed to download a file after Action: No such file

**Comment by edmundreinhardt** [comment]
@arco400 
Arco is python3 installed?
What do you get for
`yum info python3`

**Comment by arco400** [comment]
Hi Edmund,

Yes it is installed. And running bob directly in bash works, but starting a build from vscode ends in this errormessage.

Regards, Arco


Version     : 3.6.15
Release     : 1
Size        : 139 M
Repo        : installed
From repo   : ibmi-base

**Comment by edmundreinhardt** [comment]
@worksofliam
@arco400 
I think this is because you  needs to set the PATH in .bashrc instead of in .bash_profile in order to be run during ssh commands from VS Code.

Note that you shoud have EVENTF on your command line to indicate to VS Code that you want to pull pack the eventf members that provide compile feedback.
Running the `IBM i: Launch Actions Setup` command and selecting Bob will get you the appropriate command format.
 
`OPT=*EVENTF verlibcsy=CMKASOBJ /QOpenSys/pkgs/bin/makei build`

**Comment by arco400** [comment]
Edmund, adding .bashrc with the PATH did the trick, 
Great, thank you very much!
