### ISSUE TITLE
Building dependencies during compilation

### ISSUE THREAD

**Issue by PreethiJeyaraj** [IBM/ibmi-bob#263]
Hi All,

My project application is designed such that it uses objects (Programs/Files) from multiple libraries. The dependencies are defined in Rules.mk file. During compile all, I would expect only the source in the repository to be compiled, but all the depend objects mentioned in the definition are also compiled. 
In the below example, MODULE1 is the source file that must be compiled in LIBRARY1. FILE1 resides in LIBRARY2 and its source file is not present in the git repository. However LIBRARY2 is added to the build library list.  During compilation, its throwing an error that MODULE1 compilation failed due to FILE1

MODULE1.MODULE: MODULE1.SQLRPGLE FILE1.FILE

**Comment by edmundreinhardt** [comment]
If the source for FILE1 is not in the same repository then there is no point in listing it as a dependency.  Drop that and things will work.

Note the the make philosophy is that all dependencies are checked to see if they are out of date with the source and if so they will be built first.  In your case there is no source, so this behavior is not helpful and there is no point in listing the dependency
