### ISSUE TITLE
BOB seems to not respect preUsrLibl nor postUsrLibl variable

### ISSUE THREAD

**Issue by arco400** [IBM/ibmi-bob#265]
While trying to find my way with BOB I'm struggling a bit with the library list.
I'm building from Code for IBM i.
Since our compiles need more than one library, I want to add them before the build begins.
Preferably I'd like to use replacement variables, but to minimize configuration issues during test I'm using hard library names for now.

So my iproj.json contains 

```
    "objlib": "*CURLIB",
    "curlib": "TESTAS",
    "preUsrLibl": ["CMKASDTA, CMKASREF"],
    "postUsrLibl": ["CMKASOBJ, MGGPL"]

```
The compile errorlist keeps complaining about missing tables that are located in library CMKASDTA. 
That leads me to conclude that the preUsrLibl is not set in the build.

However when I add the library list via setIBMiEnvCmd it compiles quite well.
`
"setIBMiEnvCmd": ["CHGLIBL LIBL(CMKASDTA CMKASREF CMKASOBJ MGGPL)"]
`
The same behavior occurs when I don't build from VScode, but execute it directly in bash. 

Am I doing things wrong?

**Comment by edmundreinhardt** [comment]
This about proper JSON syntax.  Note that you could use the IBM i Project Explorer to manae this using the UI and not be responsible for syntactic details.

Simply using 
```
    "objlib": "*CURLIB",
    "curlib": "TESTAS",
    "preUsrLibl": ["CMKASDTA", "CMKASREF"],
    "postUsrLibl": ["CMKASOBJ", "MGGPL"]

```
[ ] bracket contain a list of items separated by , (comma) and in your case each string entry (library name) needed to be enclosed in their own set of quotes
@arco400

**Comment by arco400** [comment]
Thanks @edmundreinhardt 

It seems I have mixed up with the example from https://ibm.github.io/ibmi-bob/#/prepare-the-project/iproj-json where it has even no array brackets around it.

```
    "preUsrlibl": "&accounting, ACMEUTIL",
    "postUsrlibl": "&tax",

```
However:

```
    "preUsrLibl": "CMKASDTA, CMKASREF",
    "postUsrLibl": "CMKASOBJ, MGGPL",

```
nor 

```
    "preUsrLibl": ["CMKASDTA", "CMKASREF"],
    "postUsrLibl": ["CMKASOBJ", "MGGPL"],

```
do help here. 

I keep getting *RNF2120 40 a 000016  External descriptions for file RELATMAS not found;
When I set the library list through setIBMiEnvCmd the program compiles fine.

[joblog.json](https://github.com/IBM/ibmi-bob/files/13247379/joblog.json)
[TESTREL01.PGM.evfevent.txt](https://github.com/IBM/ibmi-bob/files/13247380/TESTREL01.PGM.evfevent.txt)
[TESTREL01.PGM.splf.txt](https://github.com/IBM/ibmi-bob/files/13247381/TESTREL01.PGM.splf.txt)

**Comment by edmundreinhardt** [comment]
Here is an example of me having 2 libraries that have programs and data respectively
Note that the data library is only in the preUsrLibl and that the databases are found at compile time
See https://github.com/edmundreinhardt/payroll-bob for how I did it.

**Comment by edmundreinhardt** [comment]
![image](https://github.com/IBM/ibmi-bob/assets/11184579/1c35cc4b-a46c-42d5-b37d-2e8fb812143a)

**Comment by edmundreinhardt** [comment]
@arco400 Let me know if this resolves your questions?

**Comment by arco400** [comment]
Hi @edmundreinhardt 

My apologies for the long delay in response.

Yes, I managed to build your example, and was also able to use multiple libraries in the preUsrlibl variable. Thanks!

The example did not run for me without some changes, please allow me to add a few comments:

- The MSTDSP display file depends on the data tables, and since it is compiled before the tables the tables have to be added as dependency in the rules.mk in QDDSSRC.
- The PAYROLL compile was not able to find the include file QPROTOSRC,ERRORTABLE because of its naming format which of course does not work with an ifs compile.

My configuration is that I do development in local files with VScode on my workstation.
I thought of adding a conditional compilation directive, so that I can temporary maintain a kind of compatibility for the qsys style compiles.
So I changed the include in the PAYROLL source:

`  /IF NOT DEFINED(IFSCOMPILE)
    /include ./qprotosrc/errortable.rpgleinc
  /ELSE
    /include QPROTOSRC,ERRORTABLE
  /ENDIF
`

And then tried to add the definition for IFSCOMPILE as a compile setting in the rules.mk.

`  PAYROLL.PGM: private DEFINE := IFSCOMPILE
  PAYROLL.PGM: PAYROLL.pgm.RPGLE
`
However that did not work. Is it possible to achieve something like this?

**Comment by edmundreinhardt** [comment]
Arco,
Thanks for pointing this out.  I had fixed this but neglected to push my commit to github.
The solution is far simpler.  We are only ever going to build this from the IFS, so we change to the IFS path.
Liam's SourceOrbit actually does this automatically.
And the IBM i Project Explorer extension now invokes the SourceOrbit to make that fix when migrating. (I highly recommend installing it if you want to develop on the IFS)
The SourceOrbit can also generate the Rules.mk correctly (it analyzes all dependencies) I have not incorporated this into Project Explorer yet, but it can be done via command line. https://github.com/IBM/sourceorbit


Does this resolve your questions

**Comment by arco400** [comment]
Thanks @edmundreinhardt I was not aware of the SourceOrbit project, thanks for pointing me in that direction. I'll definitely give that a try.
