### ISSUE TITLE
Text Description not working for rpgle programs created with CRTBNDRPG

### ISSUE THREAD

**Issue by JDubbTX** [IBM/ibmi-bob#268]
In this example rules.mk, in my qrpglesrc folder, the TEXT description is working for the SQLRPGLE programs and modules, but the non sql rpg program **RPGPGM2** created with CRTBNDRPG doesn't get the text description.

qrpglesrc/Rules.mk:
```
BASE64TST.PGM: BASE64TST.PGM.SQLRPGLE
BASE64TST.PGM: TEXT = Demo of BASE64 SQL Functions
PRINTER.MODULE: PRINTER.RPGLE
PRINTER.MODULE: TEXT = Printer Procedures
RPGPGM1.PGM: RPGPGM1.PGM.SQLRPGLE
RPGPGM1.PGM: TEXT = RPG Program One
RPGPGM2.PGM: RPGPGM2.PGM.RPGLE
RPGPGM2.PGM: TEXT = RPG Program Two
```

full code is here:  https://github.com/JDubbTX/IBMiExamples/tree/main/qrpglesrc

**Comment by edmundreinhardt** [comment]
@irfanshar How did your investigation go.

**Comment by edmundreinhardt** [comment]
@JDubbTX Good news.  With the latest version of BOB, you can embed the text at the top of your source file and then you don't need  to update the Rules.mk file any more.

**Comment by JDubbTX** [comment]
@edmundreinhardt what specific version is this? 2.4.22-1?  Is there an example source file that has the text embedded in it?

**Comment by edmundreinhardt** [comment]
This is now fully supported even with comments at top of source as imported via `cvtsrcpf`
