### ISSUE TITLE
Python Errors In Build

### ISSUE THREAD

**Issue by SJLennon** [IBM/ibmi-bob#271]
Trying again to build the "bob-recursive-example" on PUB400.COM, Bob version 2.4.19.

Cloned from Github to my Win 10 PC.
Opened directory in VS Code.
Connected to PUB400 in the Code for IBM i extension. Build with Ctrl+e and "bob build" which looks like this from actions.json:

    {
        "command": "err=*EVENTF lib1=&CURLIB makei build",
        "deployFirst": true,
        "environment": "pase",
        "extensions": [
            "GLOBAL"
        ],
        "name": "bob build",
        "postDownload": [
            ".logs/",
            ".evfevent/"
            ]
    },
 There are a large number of errors, because SAMREF did not compile: 
![image](https://github.com/IBM/ibmi-bob/assets/67484051/79fc3add-62a1-4abe-8f89-f422b1ce46ce)

In the logs directory SAMREF.splf  shows python errors:

```
Traceback (most recent call last):
  File "/QOpenSys/pkgs/lib/bob/src/makei/crtfrmstmf.py", line 452, in <module>
    cli()
  File "/QOpenSys/pkgs/lib/bob/src/makei/crtfrmstmf.py", line 336, in cli
    handle = CrtFrmStmf(srcstmf_absolute_path, args.object.strip(),
  File "/QOpenSys/pkgs/lib/bob/src/makei/crtfrmstmf.py", line 75, in __init__
    ccsid = retrieve_ccsid(srcstmf)
  File "/QOpenSys/pkgs/lib/bob/src/makei/crtfrmstmf.py", line 360, in retrieve_ccsid
    return _get_attr(srcstmf)["CCSID"]
  File "/QOpenSys/pkgs/lib/bob/src/makei/crtfrmstmf.py", line 350, in _get_attr
    stream = os.popen(f'/QOpenSys/usr/bin/attr {srcstmf}')
  File "/QOpenSys/pkgs/lib/python3.9/os.py", line 983, in popen
    proc = subprocess.Popen(cmd,
  File "/QOpenSys/pkgs/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/QOpenSys/pkgs/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/bin/sh'

```
I can simply compile just SAMREF and it completes successfully.

If I now try to build the entire project I still get a number of errors (looks like mostly files based on SAMREF):

Objects:             31 failed 7 succeed 38 total
 > Failed objects:    VATDEF.FILE FAMILLY.FILE CUSTOMER.FILE PARAMETER.FILE PROVIDER.FILE PRO201D.FILE PAR201.MODULE ORD100C.PGM ORD100C2.PGM ORD500C.PGM COUNTRY.FILE ORDER.FILE DETORD.FILE ARTIPROV.FILE COU301D.FILE ART202D.FILE COU300.MODULE COU301.MODULE FCOUNTRY.SRVPGM PRO202.MODULE PAR200.MODULE LOG100.PGM ORD101.PGM ORD200.PGM ORD201.PGM ORD202.PGM ORD900.PGM ORD901.PGM ARTLSTDAT.FILE ORD701.PGM ORDERCUS.FILE
Build Completed!

I think all of the file build have failed.  The .logs splfs that I have examined have python errors similar to the original SAMREF.splf above.  As with SAMREF, I can create them individually with CTRL+e and the Code for IBM i "bob compile" command .

```
{
        "command": "err=*EVENTF makei compile -f &BASENAME -e lib1=&CURLIB",
        "deployFirst": true,
        "environment": "pase",
        "extensions": [
            "GLOBAL"
        ],
        "name": "bob compile",
        "postDownload": [
            ".logs/",
            ".evfevent/"
            ]
    
```

**Comment by edmundreinhardt** [comment]
Hi Sam, do you have sufficient authority to run /bin/sh ?

**Comment by SJLennon** [comment]
@edmundreinhardt 
Does this help any?  (I'm not a huge *nix expert.)

```
-bash-5.1$ /bin/sh
-bash: /bin/sh: Permission denied
-bash-5.1$ ls -dl /bin
lrwxrwxrwx 1 qsys 0 16 Sep  4  2016 /bin -> /usr/bin

-bash-5.1$ ls -l /bin/sh
lrwxrwxrwx 1 qsys 0 62 Apr 23  2016 /bin/sh -> /QSYS.LIB/QSHELL.LIB/QZSHSH.PGM
-bash-5.1$ ls -dl /bin/sh
lrwxrwxrwx 1 qsys 0 62 Apr 23  2016 /bin/sh -> /QSYS.LIB/QSHELL.LIB/QZSHSH.PGM

-bash-5.1$ ls -dl /usr/bin
drwxr-sr-x 2 qsys 0 90112 Mar  9  2023 /usr/bin
-bash-5.1$ ls -dl /usr/bin/sh
lrwxrwxrwx 1 qsys 0 62 Apr 23  2016 /usr/bin/sh -> /QSYS.LIB/QSHELL.LIB/QZSHSH.PGM

                           Display Object Authority                       
                                                                          
Object . . . . . . . :   QZSHSH          Owner  . . . . . . . :   QSYS    
  Library  . . . . . :     QSHELL        Primary group  . . . :   *NONE   
Object type  . . . . :   *PGM            ASP device . . . . . :   *SYSBAS 
                                                                          
Object secured by authorization list  . . . . . . . . . . . . :   *NONE   
                                                                          
                         Object                                           
User        Group       Authority                                         
*PUBLIC                 *USE                                              
```


Does this help any?

**Comment by edmundreinhardt** [comment]
That is good  Sam.  You do have authority to run /bin/sh.  I realized that the question I should have been thinking of is, why you are running /bin/sh.  So that is the older shell (that can run *ix commands) and BOB takes advantage of the newer shell called `bash`.  
One of the prerequisites that we document is the Prerequisites https://ibm.github.io/ibmi-bob/#/getting-started/prerequisites?id=install-bash
Please install bash and let me know if that resolves your issue

**Comment by SJLennon** [comment]
@edmundreinhardt 
I am running bash. You can see that from the prompts above where I provided the ls outputs.

I also use Code for IBMi regularly and it uses bash.

Here's a screen capture from a PuTTY session that provides more info:
```
Authenticating with public key "rsa-key-20231122"
-bash-5.1$ echo $SHELL
/QOpenSys/pkgs/bin/bash
-bash-5.1$ echo $PATH
/QOpenSys/pkgs/bin/:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
-bash-5.1$
-bash-5.1$ makei --version
Bob version 2.4.19
-bash-5.1$

```
Happy to provide any more info that might help.  However, I am running on PUB400.COM where I have limited authority.

Before I posted, I just tried again a build of SAMREF, which triggers a build of all dependents.  Below is the top of the build output.  I seems like a few files compiled correctly using "`crtfrmstmf --ccsid *JOB`" but VATDEF failed using "`crtfrmstmf --ccsid 297`" and has the Python error.  

ARTICLE, which did get built with "`crtfrmstmf --ccsid *JOB`", does end up with CCSID 37, which is the CCSID of my user profile. VATDEF is in the `functionsVAT` directory which contains an `.ibmi.json` which specifies "`tgtCcsid": "500`".  I'm not sure why VATDEF specified CCSID 297 but might this be significant?
```
Running Action: bob build (10:01:34 AM)
Working directory: /home/lennons/bob-recursive-example
Commands:
	err=*EVENTF lib1=LENNONS1 makei build

> /QOpenSys/pkgs/bin/make -k BUILDVARSMKPATH="/tmp/tmpv5otc1jv" -k BOB="/QOpenSys/pkgs/lib/bob" -f "/QOpenSys/pkgs/lib/bob/src/mk/Makefile" all
=== Creating PF [SAMREF.PF] in LENNONSB
/QOpenSys/pkgs/lib/bob/src/scripts/crtfrmstmf --ccsid *JOB -f /home/LENNONS/bob-recursive-example/common/SAMREF.PF -o SAMREF -l LENNONSB -c CRTPF -p "AUT() DLTPCT(*NONE) OPTION(*EVENTF *SRC *LIST) REUSEDLT(*NO) SIZE() TEXT( )"
✓ SAMREF.FILE was created successfully!

=== Creating PF [ARTICLE-Article_File.PF] in LENNONSB
/QOpenSys/pkgs/lib/bob/src/scripts/crtfrmstmf --ccsid *JOB -f /home/LENNONS/bob-recursive-example/QDDSSRC/ARTICLE-Article_File.PF -o ARTICLE -l LENNONSB -c CRTPF -p "AUT() DLTPCT(*NONE) OPTION(*EVENTF *SRC *LIST) REUSEDLT(*NO) SIZE() TEXT(Article File )"
✓ ARTICLE.FILE was created successfully!

=== Creating LF [ARTICLE1-Article_File.LF] in LENNONSB
/QOpenSys/pkgs/lib/bob/src/scripts/crtfrmstmf --ccsid *JOB -f /home/LENNONS/bob-recursive-example/QDDSSRC/ARTICLE1-Article_File.LF -o ARTICLE1 -l LENNONSB -c CRTLF -p "AUT() OPTION(*EVENTF *SRC *LIST) TEXT(Article File )"
✓ ARTICLE1.FILE was created successfully!

=== Creating RPG module [ART300-Function_Article.RPGLE]
crtrpgmod module(LENNONSB/ART300) srcstmf('/home/LENNONS/bob-recursive-example/QRPGLESRC/ART300-Function_Article.RPGLE') AUT() DBGVIEW(*ALL) OPTIMIZE() OPTION(*EVENTF) OUTPUT(*PRINT) TEXT('Function Article ') TGTCCSID(297 ) TGTRLS() INCDIR('includes' 'QPROTOSRC') DEFINE()
✓ ART300.MODULE was created successfully!

=== Creating PF [vatdef.pf] in LENNONSB
/QOpenSys/pkgs/lib/bob/src/scripts/crtfrmstmf --ccsid 297 -f /home/LENNONS/bob-recursive-example/functionsVAT/vatdef.pf -o VATDEF -l LENNONSB -c CRTPF -p "AUT() DLTPCT(*NONE) OPTION(*EVENTF *SRC *LIST) REUSEDLT(*NO) SIZE() TEXT( )"
✕ Failed to create VATDEF.FILE!

CPFA0A9: Object not found.  Object is /QSYS.LIB/LENNONSB.LIB/EVFEVENT.FILE/VATDEF.MBR.
CPFA097: Object not copied.  Object is /QSYS.LIB/LENNONSB.LIB/EVFEVENT.FILE/VATDEF.MBR.
make: *** [/QOpenSys/pkgs/lib/bob/src/mk/Makefile:67: VATDEF.FILE] Error 255
=== Creating PF [FAMILLY.PF] in LENNONSB
/QOpenSys/pkgs/lib/bob/src/scripts/crtfrmstmf --ccsid 297 -f /home/LENNONS/bob-recursive-example/QDDSSRC/FAMILLY.PF -o FAMILLY -l LENNONSB -c CRTPF -p "AUT() DLTPCT(*NONE) OPTION(*EVENTF *SRC *LIST) REUSEDLT(*NO) SIZE() TEXT(Functions Family)"
✕ Failed to create FAMILLY.FILE!

CPFA0A9: Object not found.  Object is /QSYS.LIB/LENNONSB.LIB/EVFEVENT.FILE/FAMILLY.MBR.
CPFA097: Object not copied.  Object is /QSYS.LIB/LENNONSB.LIB/EVFEVENT.FILE/FAMILLY.MBR.
make: *** [/QOpenSys/pkgs/lib/bob/src/mk/Makefile:67: FAMILLY.FILE] Error 255
=== Creating PF [CUSTOMER.PF] in LENNONSB
/QOpenSys/pkgs/lib/bob/src/scripts/crtfrmstmf --ccsid 297 -f /home/LENNONS/bob-recursive-example/QDDSSRC/CUSTOMER.PF -o CUSTOMER -l LENNONSB -c CRTPF -p "AUT() DLTPCT(*NONE) OPTION(*EVENTF *SRC *LIST) REUSEDLT(*NO) SIZE() TEXT(Functions Customer)"
✕ Failed to create CUSTOMER.FILE!
```

**Comment by SJLennon** [comment]
@edmundreinhardt 
FWIW:  I have similar issues with /bin/sh when trying to start the Debug Service on PUB400.
https://github.com/codefori/vscode-ibmi/issues/1761

**Comment by JDubbTX** [comment]
Per discussions on Ryver, I think standardizing the shebang on all Bob scripts to use `#!/usr/bin/bash` would clear up this problem.  I'll try and make a PR in the coming days for this.  We noticed some of the Bob scripts have ` #!/usr/bin/env sh ` and some of them have the bash shebang.

**Comment by edmundreinhardt** [comment]
I welcome a PR

**Comment by SJLennon** [comment]
I have tried building bob-recursive-example using 2.4.23 and with 2.4.23 with the bash consistency changes.
In both cases I get 
```
Objects:             15 failed 93 succeed 108 total
 > Failed objects:    VATDEF.FILE PRO201.MODULE VERIFY.PGM PAR201.MODULE ORD100C.PGM ORD100C2.PGM ORD500C.PGM ORD101D.FILE LOG100.PGM ORD101.PGM ORD200.PGM ORD201.PGM ORD202.PGM ORD900.PGM HEB.PGM
Build Completed!
```

@edmundreinhardt Not sure where we stand on this or if I should wait for a new release as mentioned in #288. I can provide more info on the  failures if you think it would help.

**Comment by SJLennon** [comment]
@edmundreinhardt 
Update on bob-recursive-example on PUB400.
Holger has updated/repaired a PASE problem and applied PTFs.  Now a build using the latest bob-recursive-example and bob 2.4.5 builds almost perfectly:
`Failed objects:    PRO201.MODULE VERIFY.PGM.`
Both are Cobol 
PRO201 has CEE9901: Application error.  MCH1210 unmonitored by QQDAPROC at statement *N, instruction X'02FB'
VERIFY seems to have coding errors, but not being a Cobol expert I didn't plow into it.
I think this issue can be closed.

**Comment by edmundreinhardt** [comment]
This might be due to the COBOL compiler being  out of date on PUB400
It does  build cleanly on  our test IBM i machines.

**Comment by edmundreinhardt** [comment]
Yes, I hope to get a fix out today or tomorrow latest.  I assume you are seeing TGTCCSID() with no parm.  This is causing the CRTBNDRPG to fail. A fix for this has been delivered
