### ISSUE TITLE
STREAMDTA.DTAQ as DTAQ is not a recognized file extension

### ISSUE THREAD

**Issue by jonnyz32** [IBM/ibmi-bob#288]
Got this error when trying to compile this German file
<img width="893" alt="image" src="https://github.com/IBM/ibmi-bob/assets/42983653/d3207d5e-03c7-420c-9e5b-8fdcaadfc8cd">

**Comment by edmundreinhardt** [comment]
Yes, I need to release the next version of BOB.  A customer added support for DTAQ objects.
When I went to release, I found some other regressions that I am resolving.  Once a new BOB is deployed this problem will disappear

**Comment by JDubbTX** [comment]
> Yes, I need to release the next version of BOB. A customer added support for DTAQ objects. When I went to release, I found some other regressions that I am resolving. Once a new BOB is deployed this problem will disappear

@edmundreinhardt I've noticed some other issues that came about relating to CCSID for bound rpg programs.  If I test with tag v2.4.23 it works fine but when I test with main it breaks.  Is this the other regressions you are resolving?

**Comment by JDubbTX** [comment]
@edmundreinhardt this was with what is in master right now:

<img width="533" alt="image" src="https://github.com/IBM/ibmi-bob/assets/56802156/8386c2c3-fcd4-4825-a755-bf5214cebed0">

And this is when I ` git checkout tags/v2.4.23`

<img width="537" alt="image" src="https://github.com/IBM/ibmi-bob/assets/56802156/e22e8524-1e2e-46e6-aa14-7c0b289796f1">

**Comment by edmundreinhardt** [comment]
It is fixed on `main` now.  Feel free to try it @JDubbTX 
I have to finish merging in the other PR which is still not working and then I will release.

**Comment by JDubbTX** [comment]
> It is fixed on `main` now. Feel free to try it @JDubbTX I have to finish merging in the other PR which is still not working and then I will release.

Retested Master on PUB400 and works great!  Thanks!

**Comment by edmundreinhardt** [comment]
released v2.4.25 with support and fixes for all issues mentioned
@JDubbTX @jonnyz32
