### ISSUE TITLE
crtfrmstmf: error: argument --ccsid: expected one argument

### ISSUE THREAD

**Issue by arco400** [IBM/ibmi-bob#300]
BOB Version 2.4.25.

When running build all from VS Code, for the payroll-bob example, the compile of MSTDSP is failing with the following error in MSTDSP.log:

`
crtfrmstmf: error: argument --ccsid: expected one argument
`

The build log contains:

`
=== Creating DSPF [MSTDSP.DSPF] in BOBOBJ
/QOpenSys/pkgs/lib/bob/src/scripts/crtfrmstmf --ccsid -f /home/SIMONSEA/builds/payroll-bob/QDDSSRC/MSTDSP.DSPF -o MSTDSP -l BOBOBJ -c CRTDSPF -p "ENHDSP(*YES) RSTDSP(*YES) DFRWRT(*YES) AUT() OPTION(*EVENTF *SRC *LIST) TEXT( )"
✕ Failed to create MSTDSP.FILE!
`

**Comment by edmundreinhardt** [comment]
It seems that a `tgtccsid` of empty string was specified in the  `.ibmi.json` or the `iproj.json`
Can you please show me what those files contain for this failure?

It looks like BOB should handle that more graciously and default to the Job CCSID if there is an empty string by accident

**Comment by arco400** [comment]
Due to the ModuleNotFoundErro issue 304 I had switched back to version 2.3.9-1.
I am just trying to build the unmodified payroll-bob project from GitHub, and it's ibmi.json file contains 37 as tgtccsid.

Build all gives me now the result below. But perhaps that is not representative since it is not the same bob version as the error initially occured on.

`
Action: Build all (11:26:19 PM)
Working directory: /home/simonsea/builds/payroll-bob
Commands:
                OPT=*EVENTF BUILDLIB=QGPL /QOpenSys/pkgs/bin/makei build

> make -k BUILDVARSMKPATH="/tmp/tmp0a0g83w3" -k BOB="/QOpenSys/pkgs/lib/bob" -f "/QOpenSys/pkgs/lib/bob/mk/Makefile" all
make: Nothing to be done for 'all'.
Objects:             0 failed 0 succeed 0 total
Build Completed!

Fetching errors from .evfevent.
Downloaded files as part of Action: .logs, .evfevent
`

**Comment by edmundreinhardt** [comment]
In the scenario above it seems that nothing was out of date, so nothing needed to be built.

**Comment by edmundreinhardt** [comment]
So I just test the https://github.com/edmundreinhardt/payroll-bob
with bob 2.4.26
and I get
<img width="759" alt="image" src="https://github.com/IBM/ibmi-bob/assets/11184579/495a9354-f8f0-4eb8-a0b7-14ddc8e79fe9">

Notice that everything built cleanly but there seemed to be an issue with downloading the event file for MSTDSP.  But it had no errors.

**Comment by edmundreinhardt** [comment]
I introduced an error for MSTDSP and it showed the error correctly
<img width="603" alt="image" src="https://github.com/IBM/ibmi-bob/assets/11184579/8b2df328-0e24-478a-bf44-dbf908a672ba">

@arco400 Are you using the IBM i Project Explorer VS Code Extension. It really makes it so much easier.

**Comment by arco400** [comment]
@edmundreinhardt I have even deleted the target build folder to be sure that I would build from scratch. But it gives me the same result.

I have the IBM i project explorer extension installed. What would that help for this situation?
I do not see an "IBM Deployment" tab as in your screenshots. How can I activate that?

![image](https://github.com/IBM/ibmi-bob/assets/134314956/3d7f96ad-38ff-4c88-9c81-1868867c4594)

**Comment by edmundreinhardt** [comment]
Go to the Output tab and select 'IBM i Deployment'
<img width="809" alt="image" src="https://github.com/IBM/ibmi-bob/assets/11184579/cc2990c1-6180-46bd-a443-c94f9cbfdc75">

**Comment by edmundreinhardt** [comment]
@arco400 What type of deployment are you using? 
<img width="289" alt="image" src="https://github.com/IBM/ibmi-bob/assets/11184579/dd7b35ae-e688-4580-a517-925b5016e493">

**Comment by edmundreinhardt** [comment]
to trigger a full build you could clear the target objects in the library or touch all of the source

**Comment by arco400** [comment]
> to trigger a full build you could clear the target objects in the library or touch all of the source

@edmundreinhardt sorry I did not mention, but I had emptied that as well. My target lib is BOBDTA (and set as *CURLIB)

I am deploying by the "build all" command, and then deploy "all files".

![image](https://github.com/IBM/ibmi-bob/assets/134314956/9862c765-fba7-4c4a-9107-22fcab275862)

![image](https://github.com/IBM/ibmi-bob/assets/134314956/91677de7-0730-49d1-9fcb-8f1b51370720)


The IBM i deployment window reports:

`Deployment started using method "compare"

Remote directory is empty; switching to 'deploy all'
Created deployment tarball C:\Users\Simonsea\AppData\Local\Temp\tmp-19140-gwbNBLYMW3yi-.tar
Uploaded deployment tarball as /tmp/deploy_O_if49o18r.tar
15 file(s) uploaded to /home/simonsea/builds/payroll-bob
	.ibmi.json
	.vscode/actions.json
	.vscode/rpglint.json
	QDDSSRC/MSTDSP.DSPF
	QDDSSRC/Rules.mk
	QPROTOSRC/ERRORTABLE.RPGLEINC
	QRPGLESRC/PAYROLL.pgm.RPGLE
	QRPGLESRC/Rules.mk
	QSQLSRC/.ibmi.json
	QSQLSRC/EMPMST.TABLE
	QSQLSRC/PRJMST.TABLE
	QSQLSRC/RSNMST.TABLE
	QSQLSRC/Rules.mk
	Rules.mk
	iproj.json

/tmp/deploy_O_if49o18r.tar deleted
C:\Users\Simonsea\AppData\Local\Temp\tmp-19140-gwbNBLYMW3yi-.tar deleted

Deployment finished at 3:25:34 PM`

And the Terminal window reports:

`Running Action: /QOpenSys/pkgs/bin/makei build (3:25:35 PM)
Working directory: /home/simonsea/builds/payroll-bob
Commands:
                /QOpenSys/pkgs/bin/makei build

> make -k BUILDVARSMKPATH="/tmp/tmp56_2k7bo" -k BOB="/QOpenSys/pkgs/lib/bob" -f "/QOpenSys/pkgs/lib/bob/mk/Makefile" all
make: Nothing to be done for 'all'.
Objects:             0 failed 0 succeed 0 total
Build Completed!

Fetching errors from .evfevent.
Downloaded files as part of Action: .logs, .evfevent`
