### ISSUE TITLE
Ability to override settings on SQL table build

### ISSUE THREAD

**Issue by arco400** [IBM/ibmi-bob#313]
When I create a table with BOB, how can I override the compile settings?

In rules.mk I have:

`docqumtd.file: private COMMIT := *CHG`
`docqumtd.file: docqumtd.table`

This results in creation of the table, however I need to run this under commitment, so COMMIT(*CHG)

`=== Creating SQL TABLE from Sql statement [docqumtd.table] in CMKTSDTA`
`RUNSQLSTM srcstmf('/home/SIMONSEA/builds/app/src/dta/docqumtd.table') DBGVIEW(*SOURCE) TGTRLS() OUTPUT(*PRINT) MARGINS(1024) COMMIT(*NONE )`
`✓ DOCQUMTD.FILE was created successfully!`

How can I achieve this?

**Comment by edmundreinhardt** [comment]
base onhttps://vscode.dev/github/IBM/ibmi-bob/blob/fix/issue314_for_pseudo_source_respect_exit_code/src/mk/def_rules.mk#L439-L440
I would have expected that to work.
@irfanshar could you take a look?
