### ISSUE TITLE
Compile errors when `.evfevent` directory does not exist

### ISSUE THREAD

**Issue by SanjulaGanepola** [IBM/ibmi-bob#316]
It looks like the `.evfevent` directory is not properly created which results in the following errors:

![image](https://github.com/IBM/ibmi-bob/assets/32170854/bfdacea5-1b9b-486b-8556-78897dab23f7)

**Comment by irfanshar** [comment]
Closing this issue as investigation with @SanjulaGanepola determined that the issue was in https://github.com/IBM/vscode-ibmi-projectexplorer.

This issue is now being tracked here https://github.com/IBM/vscode-ibmi-projectexplorer/issues/536
