### ISSUE TITLE
Using a project wide TGTRLS() value has no effect

### ISSUE THREAD

**Issue by ScottA678** [IBM/ibmi-bob#336]
Using this syntax in the ```/BLD/Tst/QRPGLESRC/Rules.mk``` file seems to have no effect on the outcome.

```
PROJECT_TGTRLS := *PRV

%.MODULE: private TGTRLS := $(PROJECT_TGTRLS)
%.PGM: private TGTRLS := $(PROJECT_TGTRLS)

TEST1.MODULE: TEST1.RPGLE
TEST1.PGM: TEST1.MODULE
```
The resulting module and program are created as TGTRLS(*CURRENT)

Also getting similar outcomes with DFTACTGRP() and ACTGRP() overrides

**Comment by irfanshar** [comment]
@ScottA678 
You have picked out two really cool enhancements for us to look at.
Unfortunately, variable assignment and wildcarding is currently not supported in the Rules.mk.

I have created two new issues for us to look at.
https://github.com/IBM/ibmi-bob/issues/344
https://github.com/IBM/ibmi-bob/issues/343

For now, to have your Rules.mk working, I would suggest having it as

```
TEST1.MODULE: private TGTRLS := *PRV
TEST1.PGM: private TGTRLS := *PRV

TEST1.MODULE: TEST1.RPGLE
TEST1.PGM: TEST1.MODULE
```

Understandably, this is cumbersome, so we hope to have these enhancements in soon!

**Comment by NickLitten** [comment]
Love this feature - is there a timeline for it?

If we could define variable in the root rules.mk and then reference them from subfolders... would be magical!

I specifically look for something like this at subfolder level:

%.CMD:    private TGTRLS:=$(PROJECT_TGTRLS)
%.CMD:    private PRDLIB:=$(PROJECT_PRDLIB)
%.CMD:    private BNDDIR:=$(PROJECT_BNDDIR)
%.MODULE: private TGTRLS := $(PROJECT_TGTRLS)
%.PGM:    private TGTRLS := $(PROJECT_TGTRLS)

**Comment by NickLitten** [comment]
Now that I've added that... can we add these as defaults in the root rules.mk and then just not mention them again in subfolder rules.mk files? (therefore promoting from magical to gandalfian levels)
