### ISSUE TITLE
Support lower or mixed case source file and extensions

### ISSUE THREAD

**Issue by edmundreinhardt** [IBM/ibmi-bob#44]
When I use lower case file extensions, BOB rules are not triggered.  When I use lowercase file names even with upper-case file extensions, the compile still doesn't happen.

**Comment by worksofliam** [comment]
Looks like it just needs to match the case in `Rules.mk` (even though I am on a case-insensitive file system).

**Comment by worksofliam** [comment]
I guess the make rules also need to support both cases. Otherwise, all sources have to be in uppercase.

**Comment by ThePrez** [comment]
Alternate proposal: issue a relevant warning when running on a case-insensitive FS (and suggest a case-sensitive FS)
