### ISSUE TITLE
Cannot build CMDs due to INCDIR keyword

### ISSUE THREAD

**Issue by onewheelonly** [IBM/ibmi-bob#46]
A recent commit added support for the INCDIR keyword for several commands. Unfortunately this also changed the keywords for CRTCMD:

https://github.com/IBM/ibmi-bob/blob/1053f4363e1f97ad6ecca9343e66350bb6032497/mk/def_rules.mk#L209

Since this keyword is not valid, it is no longer possible to build commands.

**Comment by onewheelonly** [comment]
If you'd like a pull request, let me know 🙂 

Also, I'm just reacquainting myself with the Bob project after a couple of years. It's nice to see that IBM have adopted it and are continuing to improve it!

**Comment by edmundreinhardt** [comment]
Good catch, I just fixed this under another issue/PR.  But please keep the feedback coming.  I am glad someone is kicking the tires.
