### ISSUE TITLE
Consider moving the wiki

### ISSUE THREAD

**Issue by worksofliam** [IBM/ibmi-bob#54]
GitHub wiki is great but hard to make contributions too.

Perhaps it’s could be moved into the root in `docs` as markdown, or maybe in another repo?

**Comment by edmundreinhardt** [comment]
I would consider that.  Why is wiki hard for you to contribute to.  Do I need to give access of some kind?

**Comment by edmundreinhardt** [comment]
I take it this is because you cannot do pull requests on the wiki repository?
OK, I will do the migration.
