### ISSUE TITLE
TEXT attribute is not extracted correctly from the filename

### ISSUE THREAD

**Issue by TongkunZhang** [IBM/ibmi-bob#75]
For `ART200-Work_with_article.PGM.SQLRPGLE`, The TEXT should be `Work with article` instead `Work with article.PGM`
![image](https://user-images.githubusercontent.com/17009902/160652511-70e34e31-e54b-4733-98c3-15684c7286bd.png)

**Comment by edmundreinhardt** [comment]
bug still exists

**Comment by edmundreinhardt** [comment]
bug still exists
