### ISSUE TITLE
V7R3 installation failure...

### ISSUE THREAD

**Issue by jimoberholtzer** [IBM/ibmi-bob#76]
bash-5.1$ system "CRTRPGMOD MODULE(CRTFRMSTMF/crtfrmstmf) SRCSTMF('QSOURCE/crtfrmstmf.rpgl                                      e') TEXT('Create From Stream File') REPLACE(*YES) DBGVIEW(*SOURCE) TGTRLS(V7R3M0                                      ) TGTCCSID(*JOB)"
CPD0043: Keyword TGTCCSID not valid for this command.
CPF0006: Errors occurred in command.
gmake: *** [makefile:17: crtfrmstmf.rpgle] Error 255
warning: %post(bob-2.2.8-0.ppc64) scriptlet failed, exit status 2
CPD0043: Keyword TGTCCSID not valid for this command.
CPF0006: Errors occurred in command.

It looks like the V7R3 installation is using a V7R4 command.  simple fix, but I have not idea how to do it.

**Comment by jimoberholtzer** [comment]
Turns out the prerequisites need to be updated by ensuring that PTF SI62605 is installed.  Since that's not on the groups or cumulative, it would need to be applied separately.

**Comment by edmundreinhardt** [comment]
Hi Jim, thanks for bringing this to our attention.  We have updated the wiki to document this prerequisite on the RPG compiler.

**Comment by edmundreinhardt** [comment]
https://github.com/IBM/ibmi-bob/wiki/Installing-IBM-i-prerequisites#ile-rpg-prerequisites
